import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
if (!globalThis.crypto) Object.defineProperty(globalThis,'crypto',{value:crypto.webcrypto});
const source=rel=>fs.readFileSync(new URL('../../'+rel,import.meta.url),'utf8');
const uri=text=>'data:text/javascript;base64,'+Buffer.from(text).toString('base64');
const coreUri=uri(source('site/assets/review-core.js')),authUri=uri(source('functions/_access.js'));
const C=await import(coreUri), auth=await import(authUri);
const apiSource=source('functions/review-inbox.js').replace("'./_access.js'",JSON.stringify(authUri)).replace("'../site/assets/review-core.js'",JSON.stringify(coreUri));
const {handleReview,onRequest}=await import(uri(apiSource));
const payload={schema:1,product:'pitch',source_idea_id:'2026-10-05-1',source_date:'2026-10-05',title:'Test',thesis:'Test',account:'primary',published_at:'2026-10-05T09:00:00Z',review_deadline:'2026-10-05T20:00:00Z',execution_deadline:'2026-10-05T20:00:00Z',orders:[{Idea_Id:'2026-10-05-1',Leg:1,Ticker:'XLE',Sec_Type:'STK',Action:'BUY',Entry_Type:'LIMIT',Order_Type:'LMT',TIF:'DAY',Quantity:100,Execute_On:'2026-10-05',Time_Exit_Date:'2026-10-13',Time_Exit_Order:'MOO',Risk_Amt:300.0}]};
const envelope=await C.seal(payload), key='review_inbox/v1/pitch/2026-10-05.json';
const record=()=>({schema:'review-inbox.v1',product:'pitch',date:'2026-10-05',proposals:{[envelope.id]:envelope},current_ids:[envelope.id],events:[],delivery:{delivery_id:'test'}});
class Bucket {
 constructor(){this.records=new Map([[key,{value:record(),etag:'0'}]]);this.writes=[];this.fail=false;this.hook=null;}
 async get(k){if(this.fail)throw Error('Offline');if(k==='pitch_delivery_receipts/2026-10-05.json')return {json:async()=>({status:'sent',date:'2026-10-05',delivery_id:this.receiptId||'test'})};const item=this.records.get(k);return item?{size:1000,etag:item.etag,json:async()=>structuredClone(item.value)}:null;}
 async put(k,text,options){if(this.fail)throw Error('Offline');this.writes.push({k,options});if(this.hook){const hook=this.hook;this.hook=null;hook();}const item=this.records.get(k);if(item.etag!==options.onlyIf.etagMatches)return null;const etag=String(Number(item.etag)+1);this.records.set(k,{value:JSON.parse(text),etag});return {etag};}
}
const bucket=new Bucket(),env={CHARTS:bucket},identity={subject:'verified-subject'},clock=()=> '2026-10-05T12:00:00Z';
const command={id:'a1234567-0000-4000-8000-000000000001',product:'pitch',proposal_id:envelope.id,proposal_hash:envelope.hash,expected_revision:0,decision:'approve_review',confirmed:true,reason:''};
const req=(cmd=command,headers={})=>new Request('https://review.invalid/review-inbox?date=2026-10-05',{method:'POST',headers:{Origin:'https://review.invalid','Content-Type':'application/json',...headers},body:JSON.stringify(cmd)});
let count=0;const test=async(name,fn)=>{await fn();count++;console.log('PASS '+name);};
await test('auth and store fail closed without access/config',async()=>{assert.equal((await onRequest({request:req(),env:{}})).status,503);assert.equal((await onRequest({request:req(),env:{ACCESS_TEAM_DOMAIN:'team.cloudflareaccess.com',ACCESS_AUD:'aud'}})).status,401);assert.equal((await handleReview(req(),{},identity,clock)).status,503);});
await test('missing feed remains explicit; never silent stand-down',async()=>{const r=await handleReview(new Request('https://review.invalid/review-inbox'),env,identity,clock);const d=await r.json();assert.equal(d.products[1].status,'missing');assert.equal(d.products[1].stand_down,undefined);});
await test('same-origin explicit confirmation and exact hash required',async()=>{for(const [cmd,headers] of [[command,{Origin:'https://other.invalid'}],[{...command,confirmed:false},{}],[{...command,proposal_hash:'wrong'},{}]])assert.notEqual((await handleReview(req(cmd,headers),env,identity,clock)).status,200);assert.equal(bucket.writes.length,0);});
await test('concurrent decision CAS yields one event and one conflict',async()=>{const results=await Promise.all([handleReview(req(),env,identity,clock),handleReview(req({...command,id:'a1234567-0000-4000-8000-000000000002'}),env,identity,clock)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const events=bucket.records.get(key).value.events;assert.equal(events.length,1);assert.equal(events[0].actor,identity.subject);assert.equal(events[0].execution,'not_submitted');assert.ok(bucket.writes.every(w=>w.k===key&&w.options.onlyIf.etagMatches));});
await test('duplicate click and retry retain one event',async()=>{assert.equal((await handleReview(req(),env,identity,clock)).status,200);assert.equal(bucket.records.get(key).value.events.length,1);});
await test('same id cannot switch actor or decision',async()=>{assert.equal((await handleReview(req(),env,{subject:'other'},clock)).status,409);assert.equal((await handleReview(req({...command,decision:'reject',reason:'Pass'}),env,identity,clock)).status,409);});
await test('publication race supersedes stale tab before approval write',async()=>{bucket.records.set(key,{value:record(),etag:'5'});bucket.hook=()=>{const item=bucket.records.get(key);item.value.current_ids=[];item.etag='6';};assert.equal((await handleReview(req(),env,identity,clock)).status,409);assert.equal(bucket.records.get(key).value.events.length,0);});
await test('expiry rejects pending decision; history read-only',async()=>{bucket.records.set(key,{value:record(),etag:'0'});assert.equal((await handleReview(req(),env,identity,()=>payload.review_deadline)).status,409);assert.equal((await handleReview(req(),env,identity,()=> '2026-10-06T12:00:00Z')).status,409);});
await test('storage outage cannot report success',async()=>{bucket.fail=true;assert.equal((await handleReview(new Request('https://review.invalid/review-inbox'),env,identity,clock)).status,503);assert.equal((await handleReview(req(),env,identity,clock)).status,503);bucket.fail=false;});
await test('unreconciled new delivery blocks stale review without losing history',async()=>{bucket.receiptId='new-delivery';assert.equal((await handleReview(req(),env,identity,clock)).status,409);const d=await (await handleReview(new Request('https://review.invalid/review-inbox'),env,identity,clock)).json();assert.equal(d.products[0].status,'stale');assert.equal(d.products[0].proposals[0].current,false);bucket.receiptId='test';});
await test('Python canonical decimal/Unicode envelope verifies without changing values',async()=>{const text=C.canonical(payload).replace('"Risk_Amt":300','"Risk_Amt":300.0');const hash=crypto.createHash('sha256').update(text).digest('hex');const e={payload:JSON.parse(text),canonical:text,hash,id:`pitch:${payload.source_idea_id}:${hash.slice(0,16)}`};await C.verify(e);await assert.rejects(C.verify({...e,payload:{...e.payload,account:'pa'}}));});
await test('manual Seasonal has no asserted venue execution deadline',async()=>{const e=await C.seal({...payload,product:'seasonal',account:'Unassigned',manual_only:true,execution_deadline:null});assert.equal(C.view(e,[],clock()).execution_window_closed,true);});
await test('Access returns only subject verified by signature/audience/issuer/expiry',async()=>{const pair=await crypto.webcrypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk=await crypto.webcrypto.subtle.exportKey('jwk',pair.publicKey);jwk.kid='test';const oldFetch=globalThis.fetch;globalThis.fetch=async()=>({ok:true,json:async()=>({keys:[jwk]})});const settings={ACCESS_TEAM_DOMAIN:'team.cloudflareaccess.com',ACCESS_AUD:'aud'};
 const token=async(p)=>{const head=Buffer.from(JSON.stringify({alg:'RS256',kid:'test'})).toString('base64url'),body=Buffer.from(JSON.stringify(p)).toString('base64url');const signature=await crypto.webcrypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(head+'.'+body));return head+'.'+body+'.'+Buffer.from(signature).toString('base64url');};
 const claims={sub:'signed-subject',aud:['aud'],iss:'https://team.cloudflareaccess.com',exp:Math.floor(Date.now()/1000)+300};const r=t=>new Request('https://review.invalid',{headers:{'Cf-Access-Jwt-Assertion':t}});assert.deepEqual(await auth.requireAccessIdentity(r(await token(claims)),settings),{subject:'signed-subject'});assert.equal(await auth.requireAccess(r(await token(claims)),settings),null);
 for(const bad of [{...claims,aud:['other']},{...claims,exp:0},{...claims,sub:''},{...claims,iss:'https://other.invalid'}])assert.equal((await auth.requireAccessIdentity(r(await token(bad)),settings)).status,401);globalThis.fetch=oldFetch;
});
console.log(`${count} integrated review endpoint checks passed`);
