import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
const read = path => fs.readFileSync(new URL(`../../${path}`, import.meta.url), "utf8");
const moduleUrl = source => `data:text/javascript;base64,${Buffer.from(source).toString("base64")}`;
const helperUrl = moduleUrl(read("functions/_sleeve-status.js"));
const { buildStatus, readInputs, INPUTS } = await import(helperUrl);
const now = Date.parse("2026-09-06T15:00:00Z");
const checked_at = "2026-09-06T14:30:00Z";
const tasks = Object.fromEntries(["event", "trend", "chain", "legend_signals", "legend_session", "legend_watchdog"].map(k => [k, { state: "Missing", last_result: null }]));
tasks.event = tasks.chain = { state: "Ready", last_result: 0 };
const runtime = { schema: "sleeve-runtime.v1", checked_at, tasks, event_enabled: true, trend_moo_enabled: false, legend_live_today: false };
const report = data => ({ data, uploaded: checked_at });
const inputs = { runtime: report(runtime), event: report({ asof: "2026-09-04", rows: [], positions: {} }), trend: report({ asof: "2026-08-31", positions: {}, fragility_gate: { state: "CASH", reason: "Fragility above threshold" } }), dial: report({ last_evaluated: "2026-09-04", position: "FLAT", transitions: [] }) };
const rows = x => Object.fromEntries(buildStatus(x, now).sleeves.map(row => [row.id, row]));
let s = rows(inputs);
assert.equal(s.event.deployment, "Scheduled");
assert.equal(s.event.summary, "0 actions staged · 0 intended positions");
assert.equal(s.event.health, "reported");
assert.equal(s.trend.deployment, "Legacy 9:31 execution");
assert.match(s.trend.summary, /Cash per rule/);
assert.equal(s.legend.deployment, "Not activated");
assert.equal(s.dial.deployment, "Paper only");
assert.equal(s.hedge.deployment, "Manual analysis only");
assert.equal(rows({}).event.health, "unavailable");
assert.equal(rows({}).event.deployment, "Not verified");
for (const checked of ["2026-09-06T12:00:00Z", "2026-09-07T00:00:00Z", "invalid"]) {
  assert.equal(rows({ ...inputs, runtime: report({ ...runtime, checked_at: checked }) }).legend.deployment, "Not verified");
}
assert.equal(rows({ ...inputs, runtime: report({ ...runtime, tasks: {} }) }).event.deployment, "Not verified");
assert.equal(rows({ ...inputs, event: report({ asof: "2026-08-01", rows: [], positions: {} }) }).event.health, "aging", "fresh upload cannot hide stale report");
for (const asof of ["2026-02-30", "2026-09-08", "invalid"]) assert.equal(rows({ ...inputs, event: report({ asof, rows: [], positions: {} }) }).event.health, "unavailable");
assert.equal(rows({ ...inputs, event: report({ asof: "2026-09-04", positions: {} }) }).event.health, "unavailable", "missing actions cannot appear as zero");
const moo = { ...runtime, trend_moo_enabled: true, tasks: { ...tasks, trend: { state: "Ready", last_result: 0 } } };
assert.equal(rows({ ...inputs, runtime: report(moo) }).trend.deployment, "Opening-auction runner");
assert.equal(rows({ ...inputs, runtime: report({ ...runtime, trend_moo_enabled: true }) }).trend.deployment, "Runner missing or disabled");
assert.equal(rows({ ...inputs, runtime: report({ ...moo, tasks: { ...moo.tasks, trend: { state: "Ready", last_run_at: checked_at, last_result: 1 } } }) }).trend.deployment, "Last runner failed");
assert.equal(rows({ ...inputs, runtime: report({ ...moo, tasks: { ...moo.tasks, trend: { state: "Running", last_run_at: checked_at, last_result: 267009 } } }) }).trend.deployment, "Opening-auction runner", "running is not a completed failure");
const legendTasks = { ...tasks };
for (const name of ["legend_signals", "legend_session", "legend_watchdog"]) legendTasks[name] = { state: "Ready", last_result: 0 };
assert.equal(rows({ ...inputs, runtime: report({ ...runtime, tasks: legendTasks }) }).legend.deployment, "Shadow / unarmed");
assert.equal(rows({ ...inputs, runtime: report({ ...runtime, tasks: legendTasks, legend_live_today: true }) }).legend.deployment, "Configured for live today");
assert.equal(rows({ ...inputs, runtime: report({ ...runtime, tasks: { ...legendTasks, legend_signals: { state: "Ready", last_run_at: checked_at, last_result: 1 } } }) }).legend.deployment, "Runner failure reported");
const fetched = await readInputs({ get: async key => {
  if (key === INPUTS.event) throw new Error("private provider details");
  if (key === INPUTS.trend) return { size: 999999, json: async () => { throw new Error("must not parse"); } };
  if (key === INPUTS.runtime) return null;
  return { size: 100, uploaded: new Date(checked_at), json: async () => inputs.dial.data };
} });
assert.equal(fetched.dial.data.position, "FLAT");
assert.equal(fetched.event.error, "Report unavailable");
assert.equal(fetched.trend.error, "Report exceeds the size limit");
assert.ok(!JSON.stringify(buildStatus(fetched, now)).includes("private provider"));
const routeSource = read("functions/sleeve-status.js").replace('"./_access.js"', JSON.stringify(moduleUrl(read("functions/_access.js")))).replace('"./_sleeve-status.js"', JSON.stringify(helperUrl));
const { onRequestGet } = await import(moduleUrl(routeSource));
let reads = 0;
const denied = await onRequestGet({ request: new Request("https://example.test/sleeve-status"), env: { ACCESS_TEAM_DOMAIN: "team.cloudflareaccess.com", ACCESS_AUD: "aud", CHARTS: { get: async () => { reads++; } } } });
assert.equal(denied.status, 401);
assert.equal(reads, 0, "auth must precede all object reads");
assert.equal(denied.headers.get("Cache-Control"), "no-store");

// Exercise the browser's renderer and refresh error without touching execution controls.
const callbacks = {};
const elements = Object.fromEntries(["sleeve-cards", "sleeve-updated", "sleeve-refresh"].map(id => [id, { children: [], classList: { add() {}, remove() {} }, addEventListener(name, fn) { callbacks[name] = fn; } }]));
let fail = false;
const body = buildStatus(inputs, now);
body.sleeves[0].summary = '<script>alert("x")</script>';
const context = { document: { getElementById: id => elements[id], addEventListener(name, fn) { callbacks[name] = fn; }, hidden: false }, fetch: async () => { if (fail) throw Error("offline"); return { ok: true, json: async () => body }; }, AbortSignal, setInterval() {}, Date, Set };
vm.runInNewContext(read("site/assets/sleeve-status.js"), context);
callbacks.DOMContentLoaded();
await new Promise(resolve => setImmediate(resolve));
assert.match(elements["sleeve-cards"].innerHTML, /&lt;script&gt;/);
assert.ok(!elements["sleeve-cards"].innerHTML.includes("<script>"));
assert.equal(elements["sleeve-refresh"].disabled, false);
const before = elements["sleeve-cards"].innerHTML;
elements["sleeve-cards"].children = [{}];
fail = true;
await callbacks.click();
assert.equal(elements["sleeve-cards"].innerHTML, before);
assert.match(elements["sleeve-updated"].textContent, /previous fetch/);
assert.equal(elements["sleeve-refresh"].disabled, false);
console.log("PASS sleeve status: deployment, freshness, partial failures, auth, escaping, refresh recovery");
