"""Extract reviewed function bodies for portable simulations; never imports the broker runtime."""
import argparse
import ast
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from broker_runtime.prepare_execution_repairs import patch_executor, patch_agent


def prepare(source):
    hashes = json.loads((ROOT / "broker_runtime/execution_repair_source_hashes.json").read_text())
    excluded = {"_do_trim_readd", "_apply_leg_resizes", "_resize_legs_via_owners", "_restore_leg_quantities",
                "_prepare_fast_position", "_stage_readd", "_restore_or_resize_exits", "_submit_market",
                "_live_position_for_ref", "_modify_num"}
    for name, patch in (("execute_order", patch_executor), ("exec_agent", patch_agent)):
        raw = (source / (name + ".py")).read_bytes()
        if hashlib.sha256(raw).hexdigest() != hashes[name + ".py"]:
            raise ValueError(f"reviewed original source changed: {name}")
        rendered = patch(raw.decode("utf-8-sig").replace("\r\n", "\n"))
        nodes = [n for n in ast.parse(rendered).body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
                 and not n.name.startswith("_legacy") and n.name not in excluded]
        text = ('"""Reviewed function-only candidate fixture. No imports, configuration, or entrypoint.\n\n'
                'Generated by scripts/prepare_execution_test_fixtures.py from exact pinned sources.\n'
                'Drift against a locally available reviewed source is checked by the harness.\n"""\n\n'
                + "\n\n".join(ast.get_source_segment(rendered, node) for node in nodes) + "\n")
        destination = ROOT / "tests/fixtures/execution_runtime" / (name + "_core.py")
        destination.write_text(text, encoding="utf-8")
        print(f"{destination.name}: {len(nodes)} function bodies")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    prepare(parser.parse_args().source)
