"""Create a data-free source tree for the private-site cloud pipeline.

The production workflow checks the repository out under ``source/`` and uses
this script to copy *tracked code only* into a new workspace.  Runtime data,
generated site output, local credentials, and research artifacts are never
copied.  R2 materialization happens only after this boundary is established.

The destination must be absent or empty.  We intentionally do not clean an
existing directory: a production build must never inherit files from an older
step or run.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path, PurePosixPath
from typing import Iterable


STAGE_MARKER = ".private-site-cloud-stage.json"

# Anything under these roots is runtime/generated rather than source code.
EXCLUDED_PREFIXES = (
    "data/",
    "dist/",
    "dist-shared/",
    "charts/",
    "reports/",
    "scratch/",
    "presentation/",
)
EXCLUDED_FILES = {
    ".env",
    "credentials.json",
    "atr_seasonal_ranks.csv",
    "atr_seasonal_ranks.parquet",
    "wrangler.toml",
}


def _normalise_tracked_path(value: str) -> str:
    path = PurePosixPath(value.replace("\\", "/"))
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f"unsafe tracked path: {value!r}")
    return path.as_posix()


def is_runtime_path(value: str) -> bool:
    rel = _normalise_tracked_path(value)
    return rel in EXCLUDED_FILES or rel.startswith(EXCLUDED_PREFIXES)


def git_tracked_files(source: Path) -> list[str]:
    proc = subprocess.run(
        ["git", "-c", f"safe.directory={source.as_posix()}", "ls-files", "-z"],
        cwd=source,
        check=True,
        capture_output=True,
    )
    return [part.decode("utf-8") for part in proc.stdout.split(b"\0") if part]


def _git_sha(source: Path) -> str:
    proc = subprocess.run(
        ["git", "-c", f"safe.directory={source.as_posix()}", "rev-parse", "HEAD"],
        cwd=source,
        check=True,
        capture_output=True,
        text=True,
    )
    return proc.stdout.strip()


def _write_cloud_wrangler_config(destination: Path) -> None:
    # The deployable Pages config exists only inside the isolated cloud stage.
    # Keeping it out of the normal checkout removes the accidental
    # ``wrangler pages deploy`` -> local dist/ path.
    (destination / "wrangler.toml").write_text(
        "# Generated by scripts/stage_private_site_cloud_build.py.\n"
        "# This file exists only inside the isolated GitHub Actions workspace.\n"
        "name = \"seasonals-mslade\"\n"
        "pages_build_output_dir = \"dist\"\n"
        "compatibility_date = \"2026-06-01\"\n\n"
        "[[r2_buckets]]\n"
        "binding = \"CHARTS\"\n"
        "bucket_name = \"seasonals-cache\"\n",
        encoding="utf-8",
    )


def stage_source(
    source: str | os.PathLike[str],
    destination: str | os.PathLike[str],
    *,
    tracked_files: Iterable[str] | None = None,
    source_sha: str | None = None,
) -> dict:
    src_root = Path(source).resolve()
    dst_root = Path(destination).resolve()
    if src_root == dst_root or src_root in dst_root.parents:
        raise ValueError("destination must not be the source or nested inside it")
    if dst_root.exists() and any(dst_root.iterdir()):
        raise RuntimeError(f"destination is not empty: {dst_root}")
    dst_root.mkdir(parents=True, exist_ok=True)

    tracked = list(tracked_files) if tracked_files is not None else git_tracked_files(src_root)
    copied: list[str] = []
    excluded: list[str] = []
    for raw in tracked:
        rel = _normalise_tracked_path(raw)
        if is_runtime_path(rel):
            excluded.append(rel)
            continue
        src = src_root / Path(rel)
        if not src.is_file():
            continue
        dst = dst_root / Path(rel)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        copied.append(rel)

    for forbidden in ("data", "dist", "dist-shared", "charts", "reports", "scratch"):
        if (dst_root / forbidden).exists():
            raise RuntimeError(f"runtime path leaked into cloud stage: {forbidden}")

    _write_cloud_wrangler_config(dst_root)
    marker = {
        "mode": "private-site-cloud-source",
        "source_sha": source_sha or _git_sha(src_root),
        "copied_tracked_files": len(copied),
        "excluded_runtime_files": len(excluded),
    }
    (dst_root / STAGE_MARKER).write_text(
        json.dumps(marker, indent=2, sort_keys=True), encoding="utf-8"
    )
    print(
        f"Staged {len(copied)} tracked source files at {dst_root}; "
        f"excluded {len(excluded)} runtime/generated files."
    )
    return marker


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True)
    parser.add_argument("--dest", required=True)
    args = parser.parse_args()
    stage_source(args.source, args.dest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
