"""Reviewed function-only candidate fixture. No imports, configuration, or entrypoint.

Generated by scripts/prepare_execution_test_fixtures.py from exact pinned sources.
Drift against a locally available reviewed source is checked by the harness.
"""

def in_window() -> bool:
    return START_HOUR <= datetime.datetime.now().hour < END_HOUR

def log(msg: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)

def _append_seen_unlocked(cid, ctype, state) -> None:
    """Append and durably flush one receipt while the journal lock is held."""
    with open(_SEEN_PATH, "a", encoding="utf-8") as f:
        f.write(json.dumps({"id": cid, "type": ctype, "ts": time.time(),
                            "state": state}) + "\n")
        f.flush()
        os.fsync(f.fileno())

def _claim_seen(cid, ctype) -> bool:
    """Atomically claim a command id before any possible broker subprocess.

    Returns False for an already-journaled id.  Any unreadable or unwritable
    journal raises so the caller can fail closed before execution.
    """
    with _exclusive_file_lock(_SEEN_PATH + ".lock"):
        try:
            with open(_SEEN_PATH, encoding="utf-8") as f:
                lines = f.readlines()
        except FileNotFoundError:
            lines = []
        for line in lines:
            if not line.strip():
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise RuntimeError("command receipt journal is corrupt") from exc
            if not isinstance(record, dict) or not str(record.get("id") or "").strip():
                raise RuntimeError("command receipt journal has an invalid record")
            if record.get("id") == cid:
                return False
        _append_seen_unlocked(cid, ctype, "received")
        return True

def _record_seen(cid, ctype, state) -> bool:
    """Best-effort durable completion record; the initial claim remains enough."""
    try:
        with _exclusive_file_lock(_SEEN_PATH + ".lock"):
            _append_seen_unlocked(cid, ctype, state)
        return True
    except Exception as e:  # noqa: BLE001 — received claim already prevents replay
        log(f"seen-journal write failed: {e}")
        return False

def _load_seen() -> None:
    """Seed _SEEN with command ids handled in the last 24h (restart dedup)."""
    try:
        with open(_SEEN_PATH, encoding="utf-8") as f:
            lines = f.readlines()
    except FileNotFoundError:
        return
    except Exception as e:  # noqa: BLE001
        log(f"seen-journal read failed: {e}")
        return
    cutoff = time.time() - _SEEN_WINDOW_S
    for line in lines:
        try:
            rec = json.loads(line)
        except Exception:  # noqa: BLE001 — skip torn/garbled lines
            continue
        cid = rec.get("id")
        try:
            fresh = float(rec.get("ts", 0)) >= cutoff
        except (TypeError, ValueError):
            fresh = False
        if cid and fresh and cid not in _SEEN:
            _SEEN.append(cid)
    if _SEEN:
        log(f"loaded {len(_SEEN)} recent command id(s) into dedup set")

def _schedule_window(payload: dict, now=None):
    """Return (execute_at, expires_at) as timezone-aware ET datetimes."""
    execute_at = datetime.datetime.strptime(
        f"{payload.get('execute_date', '')} {payload.get('execute_time', '')}",
        "%Y-%m-%d %H:%M",
    ).replace(tzinfo=_ET)
    grace = int(payload.get("grace_minutes") or 5)
    return execute_at, execute_at + datetime.timedelta(minutes=grace)

def _save_schedules() -> None:
    """Crash-safe snapshot. Executing records are never retried after a crash."""
    tmp = SCHEDULED_OPTIONS_PATH + ".tmp"
    rows = sorted(_SCHEDULES.values(), key=lambda r: float(r.get("created_at", 0)))[-200:]
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2, sort_keys=True)
    os.replace(tmp, SCHEDULED_OPTIONS_PATH)

def _load_schedules() -> None:
    global _SCHEDULES
    try:
        with open(SCHEDULED_OPTIONS_PATH, encoding="utf-8") as f:
            rows = json.load(f)
    except FileNotFoundError:
        _SCHEDULES = {}
        return
    except Exception as e:  # noqa: BLE001 -- corrupt state must fail closed
        log(f"scheduled-options read failed; no schedules loaded: {e}")
        _SCHEDULES = {}
        return
    loaded = {}
    changed = False
    for rec in rows if isinstance(rows, list) else []:
        cid = str(rec.get("id") or "")
        if not cid:
            continue
        if rec.get("state") == "executing":
            rec["state"] = "unknown"
            rec["detail"] = "agent restarted during execution; VERIFY IN TWS -- never auto-retried"
            changed = True
        loaded[cid] = rec
    _SCHEDULES = loaded
    if changed:
        _save_schedules()
    pending = sum(1 for r in loaded.values() if r.get("state") == "scheduled")
    if pending:
        log(f"loaded {pending} pending scheduled option intent(s)")

def _validate_scheduled_option(payload: dict, account: str, now=None):
    """Pure receipt-time validation. Live contract/quote checks happen at trigger."""
    reasons = []
    now = now or datetime.datetime.now(_ET)
    sym = str(payload.get("symbol") or "").upper().strip()
    right = str(payload.get("right") or "").upper()
    mode = str(payload.get("expiry_mode") or "")
    if account not in OPTION_ACCOUNTS:
        reasons.append(f"options execution is disabled for {account}")
    if not re.fullmatch(r"[A-Z][A-Z0-9.]{0,9}", sym):
        reasons.append("valid stock or ETF underlying required")
    if right not in ("P", "C"):
        reasons.append("right must be P or C")
    try:
        delta = float(payload.get("target_delta"))
        tolerance = float(payload.get("delta_tolerance") or 0.03)
        budget = float(payload.get("premium_budget"))
        grace = int(payload.get("grace_minutes") or 5)
        if not 0.01 <= delta <= 0.50:
            reasons.append("target_delta must be between 0.01 and 0.50")
        if not 0 < tolerance <= 0.15:
            reasons.append("delta_tolerance must be in (0, 0.15]")
        if not math.isfinite(budget) or budget <= 0:
            reasons.append("premium_budget must be > 0")
        if not 1 <= grace <= 30:
            reasons.append("grace_minutes must be from 1 to 30")
    except (TypeError, ValueError):
        budget = 0.0
        reasons.append("delta, tolerance, budget, and grace must be numbers")
    if str(payload.get("order_type") or "").upper() != "LMT":
        reasons.append("scheduled option order_type must be LMT")
    if str(payload.get("tif") or "").upper() != "DAY":
        reasons.append("scheduled option TIF must be DAY")
    if str(payload.get("timezone") or "") != "America/New_York":
        reasons.append("timezone must be America/New_York")
    try:
        execute_at, _expires_at = _schedule_window(payload, now)
        if execute_at <= now:
            reasons.append("execution time must be in the future")
        if execute_at > now + datetime.timedelta(days=366):
            reasons.append("execution time cannot be more than 366 days away")
        if execute_at.weekday() >= 5:
            reasons.append("execution date must be a weekday")
        if not datetime.time(9, 30) <= execute_at.time() <= datetime.time(15, 59):
            reasons.append("execution time must be during 09:30-15:59 ET")
    except (TypeError, ValueError):
        execute_at = None
        reasons.append("execute_date/execute_time must be YYYY-MM-DD and HH:MM")
    if mode == "min_dte":
        try:
            dte = int(payload.get("min_dte"))
            if dte != float(payload.get("min_dte")) or not 0 <= dte <= 730:
                reasons.append("min_dte must be a whole number from 0 to 730")
        except (TypeError, ValueError):
            reasons.append("min_dte must be a whole number from 0 to 730")
    elif mode == "specific":
        try:
            expiry = datetime.date.fromisoformat(str(payload.get("expiry") or ""))
            if execute_at and expiry < execute_at.date():
                reasons.append("specific expiry cannot precede execution date")
        except ValueError:
            reasons.append("specific expiry must be YYYY-MM-DD")
    else:
        reasons.append("expiry_mode must be min_dte or specific")
    if budget > 0:
        if not _uncapped_options(account) and budget > _acct_max_opt_risk(account):
            reasons.append(f"premium budget ${budget:,.0f} exceeds ${_acct_max_opt_risk(account):,.0f} {account} cap")
        _positions, nlv = _account_state(account)
        needs_ack = not nlv or budget > 0.05 * float(nlv)
        if _uncapped_options(account) and needs_ack and payload.get("risk_ack") is not True:
            reasons.append("risk_ack required: NLV unavailable or premium target exceeds 5% of NLV")
    return reasons

def _store_schedule(cmd: dict):
    execute_at, expires_at = _schedule_window(cmd.get("payload") or {})
    rec = {
        "id": cmd.get("id"), "account": cmd.get("account"),
        "payload": cmd.get("payload") or {}, "state": "scheduled",
        "created_at": time.time(), "execute_at": execute_at.timestamp(),
        "expires_at": expires_at.timestamp(),
    }
    _SCHEDULES[rec["id"]] = rec
    _save_schedules()
    return rec

def _verify(signed: str, sig: str) -> bool:
    if not STATUS_TOKEN:
        return False
    want = hmac.new(STATUS_TOKEN.encode(), signed.encode(), hashlib.sha256).hexdigest()
    return hmac.compare_digest(want, sig or "")

def _describe(cmd: dict) -> str:
    """What this command WOULD do, as plain text (no order is built)."""
    t, p, acct = cmd.get("type"), (cmd.get("payload") or {}), cmd.get("account")
    if t == "echo":
        return f"echo: {p.get('note', '')}"
    if t in ("flatten", "close_only", "close_resize"):
        if p.get("qty") not in (None, ""):
            amt = f"{p['qty']} sh"
        else:
            frac = p.get("fraction", 1.0)
            amt = "100%" if frac in (1, 1.0, None) else f"{float(frac) * 100:.0f}%"
        ot = str(p.get("order_type") or "MKT").upper()
        px = f" @ {p.get('limit')}" if ot == "LMT" else ""
        rth = " outsideRTH" if p.get("outside_rth") else ""
        verb = {"close_only": "close only (leave orders)",
                "close_resize": "close (shrink exits first)"}.get(t, "flatten")
        return f"{verb} {amt} of {p.get('symbol', '?')} ({acct}) via {ot}{px}{rth}"
    if t == "trim_readd":
        frac = float(p.get("fraction", 0.5) or 0.5)
        suffix = " + re-add at Avg" if p.get("readd", True) else ""
        return (f"trim {frac * 100:.0f}% of {p.get('symbol', '?')} ({acct}) via MKT"
                f"{suffix}; clone bracket")
    if t == "add_to_position":
        frac = float(p.get("fraction", 1.0) or 1.0)
        return (f"add {frac:g}x to {p.get('symbol', '?')} ({acct}) via MKT; "
                "resize bracket")
    if t == "entry_bracket":
        ts = f"  time {p.get('time_stop')}" if p.get("time_stop") else ""
        symbol = p.get("symbol", "?")
        if str(p.get("sec_type", "STK")).upper() == "CASH":
            symbol = f"{symbol}/{p.get('currency', 'USD')}"
        stop_txt = (f"stop {p.get('stop')}" if p.get("stop") not in (None, "")
                    else "NO STOP")
        entry_type = str(p.get("entry_type") or "LMT").upper()
        entry_txt = (f"LMT @ {p.get('entry')}" if entry_type == "LMT"
                     else f"STP LMT trig {p.get('entry')} cap {p.get('entry_cap')}"
                     if entry_type == "STP_LMT"
                     else f"{entry_type} (risk ref {p.get('entry')})")
        unprot = ("  [UNPROTECTED]" if p.get("stop") in (None, "")
                  and p.get("target") in (None, "") and not p.get("time_stop") else "")
        return (f"{p.get('action', '?')} {p.get('quantity', '?')} {symbol} ({acct}) "
                f"{entry_txt}  {stop_txt}  target {p.get('target')}{ts}{unprot}")
    if t == "exit_attach":
        bits = [x for x in (
            f"stop {p.get('stop')}" if p.get("stop") not in (None, "") else "",
            f"target {p.get('target')}" if p.get("target") not in (None, "") else "",
            f"time {p.get('time_stop')}" if p.get("time_stop") else "") if x]
        return f"attach exits to {p.get('symbol', '?')} ({acct})  {'  '.join(bits) or '(none)'}"
    if t == "cancel":
        what = f"order {p.get('order_id')}" if p.get("scope") == "order" else f"all orders for {p.get('symbol', '?')}"
        return f"cancel {what} ({acct})"
    if t == "modify":
        return (f"modify order {p.get('order_id')} ({acct}) -> "
                f"lmt {p.get('new_limit')}  stop {p.get('new_stop')}  qty {p.get('new_qty')}")
    if t == "option_spread":
        legs = " / ".join(f"{(l.get('side') or '?')[0]}{l.get('strike')}{l.get('right')}"
                          for l in (p.get("legs") or []))
        return (f"{p.get('action', '?')} {p.get('quantity', '?')}x {p.get('symbol', '?')} "
                f"{(p.get('legs') or [{}])[0].get('expiry', '?')} combo [{legs}] "
                f"@ {p.get('limit')} net ({acct}) [{p.get('structure', 'spread')}]")
    if t == "scheduled_option":
        expiry = (f"expiry {p.get('expiry')}" if p.get("expiry_mode") == "specific"
                  else f"minimum {p.get('min_dte')} DTE")
        return (f"schedule BUY ~${float(p.get('premium_budget') or 0):,.0f} {p.get('symbol', '?')} "
                f"{p.get('right', '?')} nearest {p.get('target_delta')} delta ({expiry}) "
                f"at {p.get('execute_date')} {p.get('execute_time')} ET via MKT ({acct})")
    if t == "scheduled_option_cancel":
        return f"cancel scheduled option {p.get('schedule_id', '?')} ({acct})"
    return f"unknown command type {t!r}"

def _account_state(account: str):
    b = _BOOK["book"] or {}
    for a in b.get("accounts", []):
        if a.get("key") == account:
            return a.get("positions", []), a.get("nlv")
    return [], None

def _identity_matches(rec: dict, payload: dict) -> bool:
    """Exact-enough book identity match for a confirmed position action.

    conId wins when both sides carry it.  The fallback is symbol + security type
    + expiry, which remains usable during the first snapshot after an upgrade.
    """
    sym = str(payload.get("symbol", "")).upper()
    if str(rec.get("symbol", "")).upper() != sym:
        return False
    try:
        want_cid = int(payload.get("con_id") or 0)
        got_cid = int(rec.get("con_id") or 0)
    except (TypeError, ValueError):
        return False
    if want_cid and got_cid:
        return want_cid == got_cid
    sec = str(payload.get("sec_type") or "").upper()
    if sec and str(rec.get("sec_type") or "").upper() != sec:
        return False
    currency = str(payload.get("currency") or "").upper()
    if currency and str(rec.get("currency") or "").upper() != currency:
        return False
    expiry = str(payload.get("expiry") or "").strip()
    if expiry:
        got_expiry = str(rec.get("expiry_full") or rec.get("expiry") or "")
        if not got_expiry.startswith(expiry):
            return False
    return True

def _find_positions(account: str, payload) -> list:
    poss, _ = _account_state(account)
    p = payload if isinstance(payload, dict) else {"symbol": payload}
    return [x for x in poss if _identity_matches(x, p)]

def _find_position(account: str, payload):
    matches = _find_positions(account, payload)
    return matches[0] if len(matches) == 1 else None

def _position_orders(account: str, pos: dict) -> list:
    b = _BOOK["book"] or {}
    terminal = {"CANCELLED", "APICANCELLED", "INACTIVE", "FILLED"}
    for a in b.get("accounts", []):
        if a.get("key") != account:
            continue
        return [o for o in a.get("orders", [])
                if str(o.get("status") or "").upper() not in terminal
                and _identity_matches(o, pos)]
    return []

def _fast_qty(held: int, payload: dict, *, partial: bool) -> tuple[int | None, str | None]:
    """Resolve an explicit qty or a fraction using deterministic half-up rounding."""
    raw = payload.get("qty")
    if raw not in (None, ""):
        try:
            q = float(raw)
        except (TypeError, ValueError):
            return None, "qty must be a number"
        if q <= 0 or q != int(q):
            return None, "qty must be a whole number > 0"
        n = int(q)
    else:
        default = 0.5 if partial else 1.0
        try:
            frac = float(payload.get("fraction", default) or default)
        except (TypeError, ValueError):
            return None, "fraction must be a number"
        if frac <= 0 or (partial and frac >= 1.0):
            bound = "(0, 1)" if partial else "> 0"
            return None, f"fraction must be {bound}"
        n = int(math.floor(held * frac + 0.5))
    if n <= 0:
        return None, "resolved quantity is zero"
    if partial and n >= held:
        return None, f"trim quantity {n} must be below held {held}"
    return n, None

def _bracket_snapshot(account: str, pos: dict) -> tuple[list, list[str]]:
    """Validate the visible closing bracket without trusting it for execution.

    The executor repeats this against IBKR.  Here it makes dry-run previews and
    site feedback useful while failing closed on missing protective exits or
    ambiguous OCA quantities.
    """
    reasons = []
    held = int(round(abs(float(pos.get("position") or 0))))
    close_action = "SELL" if float(pos.get("position") or 0) > 0 else "BUY"
    open_orders = _position_orders(account, pos)
    entries = [o for o in open_orders if str(o.get("action") or "").upper() != close_action]
    if entries:
        reasons.append("same-direction entry/add order already working")
    exits = [o for o in open_orders if str(o.get("action") or "").upper() == close_action]
    supported = {"STP", "LMT", "MKT"}
    if not exits:
        reasons.append("no working closing bracket")
        return exits, reasons
    if not any(
            (str(o.get("order_type") or "").upper() == "STP"
             and float(o.get("aux") or 0) > 0)
            or (str(o.get("order_type") or "").upper() == "MKT"
                and o.get("good_after"))
            for o in exits):
        reasons.append("no working price stop or scheduled time stop")
    groups = {}
    for i, o in enumerate(exits):
        typ = str(o.get("order_type") or "").upper()
        if typ not in supported:
            reasons.append(f"unsupported closing leg type {typ or '?'}")
            continue
        if typ == "MKT" and not o.get("good_after"):
            reasons.append("unscheduled working MKT closing order is ambiguous")
        try:
            qty = float(o.get("qty") or 0)
        except (TypeError, ValueError):
            qty = 0
        if qty <= 0 or qty != int(qty):
            reasons.append("closing-leg quantities must be positive whole numbers")
            continue
        group = o.get("oca_group") or f"solo:{o.get('perm_id') or o.get('order_id') or i}"
        groups.setdefault(group, []).append(int(qty))
    rung_total = 0
    for group, quantities in groups.items():
        if len(set(quantities)) != 1:
            reasons.append(f"OCA group {group} has inconsistent leg quantities")
        else:
            rung_total += quantities[0]
    if groups and rung_total != held:
        reasons.append(f"closing bracket covers {rung_total}, expected {held}")
    return exits, reasons

def _scaled_snapshot_legs(exits: list, new_total: int) -> tuple[list, str | None]:
    """Proportionally scale OCA rungs with stable largest-remainder rounding."""
    groups = {}
    order = []
    for i, leg in enumerate(exits):
        key = leg.get("oca_group") or f"solo:{leg.get('perm_id') or leg.get('order_id') or i}"
        if key not in groups:
            groups[key] = {"qty": int(float(leg.get("qty") or 0)), "legs": []}
            order.append(key)
        groups[key]["legs"].append(leg)
    if not groups:
        return [], "no closing bracket to scale"
    if new_total < len(groups):
        return [], f"quantity {new_total} is too small to preserve {len(groups)} bracket rungs"
    original = sum(groups[k]["qty"] for k in order)
    if original <= 0:
        return [], "closing bracket has no scalable quantity"
    raw = {k: new_total * groups[k]["qty"] / original for k in order}
    alloc = {k: max(1, int(math.floor(raw[k]))) for k in order}
    while sum(alloc.values()) > new_total:
        candidates = [k for k in order if alloc[k] > 1]
        if not candidates:
            return [], "bracket rung rounding is not representable"
        k = min(candidates, key=lambda x: (raw[x] - math.floor(raw[x]), order.index(x)))
        alloc[k] -= 1
    while sum(alloc.values()) < new_total:
        k = max(order, key=lambda x: (raw[x] - math.floor(raw[x]), -order.index(x)))
        alloc[k] += 1
        raw[k] = math.floor(raw[k])
    scaled = []
    for k in order:
        for leg in groups[k]["legs"]:
            scaled.append((leg, alloc[k]))
    return scaled, None

def _snapshot_leg_text(prefix: str, leg: dict, qty: int) -> str:
    typ = str(leg.get("order_type") or "").upper()
    if typ == "STP":
        price = f" @ {leg.get('aux')}"
    elif typ == "LMT":
        price = f" @ {leg.get('lmt')}"
    else:
        price = f" @ {leg.get('good_after')}" if leg.get("good_after") else ""
    oca = "  (OCA)" if leg.get("oca_group") else ""
    return f"{prefix} {typ} {qty}{price}{oca}"

def _find_order(account: str, p: dict):
    """The book's working-order record matching the payload's perm_id / order_id."""
    b = _BOOK["book"] or {}
    try:
        perm = int(p.get("perm_id") or 0)
        oid = int(p.get("order_id") or 0)
    except (TypeError, ValueError):
        return None
    for a in b.get("accounts", []):
        if a.get("key") != account:
            continue
        for o in a.get("orders", []):
            if perm and int(o.get("perm_id") or 0) == perm:
                return o
            if oid and int(o.get("order_id") or 0) == oid:
                return o
    return None

def _fut_multiplier(symbol: str):
    """(multiplier, err) for a futures root from contract_reference.json. Cached."""
    try:
        if _SPECS["map"] is None:
            from futures_sizing import load_specs
            _SPECS["map"] = load_specs()
    except Exception as e:  # noqa: BLE001
        return None, f"futures spec load failed: {e}"
    s = _SPECS["map"].get(str(symbol).upper())
    if s is None:
        return None, f"no futures spec for {symbol!r}"
    return s.multiplier, None

def _acct_max_notional(acct):
    """Validation cap: the per-account live gate when configured (mirrors
    execute_order.py's LIVE_MAX_NOTIONAL_<ACCT> / LIVE_MAX_NOTIONAL), never
    above the MAX_NOTIONAL dry-run guardrail."""
    v = (os.environ.get(f"LIVE_MAX_NOTIONAL_{str(acct or '').upper()}", "").strip()
         or os.environ.get("LIVE_MAX_NOTIONAL", "").strip())
    try:
        return min(MAX_NOTIONAL, float(v)) if v else MAX_NOTIONAL
    except ValueError:
        return MAX_NOTIONAL

def _acct_max_opt_risk(acct):
    """Per-account option-risk validation cap (mirrors execute_order.py's
    LIVE_MAX_OPT_RISK_<ACCT> / LIVE_MAX_OPT_RISK), never above the MAX_OPT_RISK
    dry-run guardrail."""
    v = (os.environ.get(f"LIVE_MAX_OPT_RISK_{str(acct or '').upper()}", "").strip()
         or os.environ.get("LIVE_MAX_OPT_RISK", "").strip())
    try:
        return min(MAX_OPT_RISK, float(v)) if v else MAX_OPT_RISK
    except ValueError:
        return MAX_OPT_RISK

def _uncapped_futures(acct):
    return str(acct or "").lower() in UNCAPPED_FUTURES_ACCOUNTS

def _uncapped_options(acct):
    return str(acct or "").lower() in UNCAPPED_OPTIONS_ACCOUNTS

def _spread_legs(p: dict):
    """(legs, reasons) — normalized option_spread legs + validation reasons.
    Mirrors execute_order._parse_spread_legs (kept in sync by hand)."""
    reasons = []
    legs = p.get("legs")
    if not isinstance(legs, list) or not (1 <= len(legs) <= 2):
        return None, ["option_spread needs one long option or one 2-leg vertical"]
    out = []
    for i, l in enumerate(legs):
        side = str(l.get("side", "")).upper()
        right = str(l.get("right", "")).upper()
        expiry = str(l.get("expiry", "")).replace("-", "").strip()
        try:
            strike = float(l.get("strike"))
            ratio = int(l.get("ratio", 1) or 1)
        except (TypeError, ValueError):
            reasons.append(f"leg {i + 1}: strike/ratio must be numbers")
            continue
        if side not in ("BUY", "SELL"):
            reasons.append(f"leg {i + 1}: side must be BUY/SELL")
        if right not in ("C", "P"):
            reasons.append(f"leg {i + 1}: right must be C/P")
        if len(expiry) != 8 or not expiry.isdigit():
            reasons.append(f"leg {i + 1}: expiry must be YYYYMMDD")
        if strike <= 0:
            reasons.append(f"leg {i + 1}: strike must be > 0")
        if ratio < 1:
            reasons.append(f"leg {i + 1}: ratio must be >= 1")
        out.append({"side": side, "right": right, "expiry": expiry,
                    "strike": strike, "ratio": ratio})
    return (out if not reasons else None), reasons

def option_combo_risk(action, limit, qty, legs):
    """Return (defined-risk dollars incl. round-trip commissions, error).

    Mirrors execute_order's deliberately narrow mapped-option whitelist.
    """
    action = str(action).upper()
    try:
        limit, qty = float(limit), int(qty)
    except (TypeError, ValueError):
        return None, "quantity/limit must be numbers"
    if action not in ("BUY", "SELL"):
        return None, "action must be BUY or SELL"
    if qty <= 0 or limit <= 0:
        return None, "quantity and limit must be > 0"
    if len(legs) not in {1, 2}:
        return None, "only one long option or one 1:1 vertical is supported"
    if any(int(l.get("ratio", 1) or 1) != 1 for l in legs):
        return None, "option ratios are not supported"
    n_contracts = qty * len(legs)
    comm = OPT_COMM_PER_CONTRACT * n_contracts * 2
    if len(legs) == 1:
        if action != "BUY" or str(legs[0].get("side") or "").upper() != "BUY":
            return None, "a single option must be a 1:1 BUY"
        return limit * 100.0 * qty + comm, None
    if len({str(leg.get("expiry") or "") for leg in legs}) != 1:
        return None, "vertical legs must share one expiry"
    if len({str(leg.get("right") or "").upper() for leg in legs}) != 1:
        return None, "vertical legs must share one option right"
    if {str(leg.get("side") or "").upper() for leg in legs} != {"BUY", "SELL"}:
        return None, "vertical needs one BUY leg and one SELL leg"
    bought = next(leg for leg in legs if str(leg["side"]).upper() == "BUY")
    sold = next(leg for leg in legs if str(leg["side"]).upper() == "SELL")
    right = str(bought["right"]).upper()
    canonical = (
        float(bought["strike"]) < float(sold["strike"])
        if right == "C"
        else float(bought["strike"]) > float(sold["strike"])
    )
    if not canonical:
        return None, "vertical legs are not in canonical debit orientation"
    width = abs(float(bought["strike"]) - float(sold["strike"]))
    if width <= 0 or limit >= width:
        return None, f"net price {limit:g} must be below vertical width {width:g}"
    unit_loss = limit if action == "BUY" else width - limit
    return unit_loss * 100.0 * qty + comm, None

def _leg_multiplier(p: dict):
    """Contract $-multiplier for notional/risk math. STK/CASH = 1; FUT looked up
    from contract_reference.json (raises via err, never a silent 1.0). Returns
    (multiplier, err)."""
    if str(p.get("sec_type", "STK")).upper() == "FUT":
        mult, err = _fut_multiplier(str(p.get("symbol", "")).upper())
        if err:
            try:
                claimed = float(p.get("fut_multiplier"))
            except (TypeError, ValueError):
                return None, err
            if not claimed > 0:
                return None, "fut_multiplier must be > 0"
            # Preview/ack math only. execute_order re-queries IBKR and cross-checks
            # the live multiplier before any order can transmit.
            return claimed, None
        return mult, None
    return 1.0, None

def _fx_usd_exposure(symbol, currency, qty, entry, stop):
    """Return (notional_usd, risk_usd) for a USD FX pair.

    CASH quantity is in base-currency units; the contract price is quote
    currency per base. Crosses without a USD leg are intentionally unsupported
    until the guardrail can convert their exposure into account currency.
    """
    base = str(symbol or "").upper()
    quote = str(currency or "").upper()
    if quote == "USD":
        return qty * entry, qty * abs(entry - stop)
    if base == "USD":
        return qty, qty * abs(entry - stop) / entry
    raise ValueError("CASH entry supports USD pairs only initially")

def _futures_size(msg: dict) -> dict:
    """Read-only risk-based futures sizing for the execution tab — no IBKR, no
    transmit. Params: symbol, entry, stop, target?, and a risk spec: `risk`
    (dollars) OR `risk_pct` (+ `account_value`, else the routed account_key's live
    NLV from the last book). Returns futures_sizing.SizeResult.as_dict() or {error}."""
    try:
        from futures_sizing import size_futures
    except Exception as e:  # noqa: BLE001
        return {"error": f"sizer import failed: {e}"}
    sym = str(msg.get("symbol", "")).strip()
    if not sym:
        return {"error": "symbol required"}
    try:
        entry, stop = float(msg.get("entry")), float(msg.get("stop"))
    except (TypeError, ValueError):
        return {"error": "entry and stop must be numbers"}
    target = None
    if msg.get("target") not in (None, ""):
        try:
            target = float(msg.get("target"))
        except (TypeError, ValueError):
            return {"error": "target must be a number"}

    risk = msg.get("risk")
    risk_pct = msg.get("risk_pct")
    account = None
    if msg.get("account_value") not in (None, ""):
        try:
            account = float(msg.get("account_value"))
        except (TypeError, ValueError):
            account = None
    if risk_pct not in (None, "") and account is None:      # fall back to live NLV
        _, nlv = _account_state(str(msg.get("account_key", "primary")))
        account = float(nlv) if nlv else None

    try:
        r = size_futures(
            sym, entry, stop, target=target,
            risk_dollars=float(risk) if risk not in (None, "") else None,
            risk_pct=float(risk_pct) if risk_pct not in (None, "") else None,
            account=account,
        )
    except (KeyError, ValueError) as e:
        return {"error": str(e)}
    return r.as_dict()

def _requested_close_qty(p: dict, held: int):
    """Shares a close ticket is asking for. None when the payload is unusable.

    Mirrors the executor's rounding exactly (explicit `qty` wins, else
    round-half-up of held x fraction) so the agent's preview, its validation
    and the live gate can never disagree about how big the close is.
    """
    raw = p.get("qty")
    if raw not in (None, ""):
        try:
            q = float(raw)
        except (TypeError, ValueError):
            return None
        if q <= 0 or q != int(q):
            return None
        return int(q)
    try:
        frac = float(p.get("fraction", 1.0) or 1.0)
    except (TypeError, ValueError):
        return None
    if frac <= 0:
        return None
    return int(math.floor(int(held) * frac + 0.5))

def _validate(cmd: dict):
    """Gatekeeper checks against the live read-only book. Returns (ok, reasons)."""
    t, p, acct = cmd.get("type"), (cmd.get("payload") or {}), cmd.get("account")
    import position_action_agent
    if position_action_agent.applies(cmd):
        return position_action_agent.validate(cmd)
    reasons = []
    if t in DISABLED_UNSAFE_MUTATIONS - {"cancel", "modify"}:
        reasons.append(
            f"{t} is disabled until it has an atomic exact-identity broker lifecycle"
        )
    if acct not in ("primary", "pa"):
        reasons.append(f"unknown account {acct!r}")
    sym = str(p.get("symbol", "")).upper()

    if t == "flatten":
        if not sym:
            reasons.append("symbol required")
        elif _find_position(acct, sym) is None:
            reasons.append(f"no open position in {sym} ({acct})")

    if t in ("close_only", "close_resize"):
        if not sym:
            reasons.append("symbol required")
        else:
            matches = _find_positions(acct, p)
            if not matches:
                reasons.append(f"no exact open position in {sym} ({acct})")
            elif len(matches) > 1:
                reasons.append(f"{len(matches)} positions match {sym}; exact con_id/expiry required")
            elif str(matches[0].get("sec_type") or "").upper() not in {
                "STK", "CASH", "FUT"
            }:
                reasons.append(
                    f"{t} supports only STK/CASH/FUT; one-leg option closes "
                    "can dismantle a hedged structure"
                )
            elif t == "close_resize":
                # close_resize resizes the exits DOWN to the remainder, and an
                # exit cannot be resized to zero -- a full close has to cancel
                # them, which is flatten's job. Caught here so the ticket fails
                # before the executor opens a live connection.
                held = int(round(abs(float(matches[0].get("position") or 0))))
                closing = _requested_close_qty(p, held)
                if closing is None:
                    reasons.append("close_resize needs a whole qty > 0 or a fraction > 0")
                elif closing > held:
                    reasons.append(f"close qty {closing} exceeds held {held} {sym}")
                elif closing == held:
                    reasons.append(
                        "close_resize is a PARTIAL close; use flatten to close the "
                        "whole position (its exits have to be cancelled, not resized)"
                    )

    if t == "exit_attach":
        stop_p, target_p, ts_p = p.get("stop"), p.get("target"), p.get("time_stop")
        have_stop, have_target = stop_p not in (None, ""), target_p not in (None, "")
        if not sym:
            reasons.append("symbol required")
            pos = None
        else:
            matches = _find_positions(acct, p)
            pos = matches[0] if len(matches) == 1 else None
            if not matches:
                reasons.append(f"no open position in {sym} ({acct})")
            elif len(matches) > 1:
                reasons.append(f"{len(matches)} positions match {sym}; exact con_id/expiry required")
        if not (have_stop or have_target or ts_p):
            reasons.append("exit_attach needs at least one of stop/target/time_stop")
        sv = tv = None
        try:
            if have_stop:
                sv = float(stop_p)
                if sv <= 0:
                    reasons.append("stop must be > 0")
            if have_target:
                tv = float(target_p)
                if tv <= 0:
                    reasons.append("target must be > 0")
        except (TypeError, ValueError):
            reasons.append("stop/target must be numbers")
        if ts_p:
            d = str(ts_p).replace("-", "").strip()[:8]
            if len(d) != 8 or not d.isdigit():
                reasons.append("time_stop must be a date (YYYY-MM-DD)")
        if pos is not None:
            if str(pos.get("sec_type") or "").upper() not in {
                "STK", "CASH", "FUT"
            }:
                reasons.append(
                    "exit_attach supports only STK/CASH/FUT; one-leg option "
                    "exits can dismantle a hedged structure"
                )
            live_position = float(pos.get("position") or 0)
            long_pos = live_position > 0
            if sv and tv and sv > 0 and tv > 0:
                if long_pos and not sv < tv:
                    reasons.append("long position needs stop < target")
                if not long_pos and not tv < sv:
                    reasons.append("short position needs target < stop")
            # Wrong-side price = the leg fills/triggers the instant it's live.
            # The book's mark can be stale -- the executor re-checks vs IBKR.
            mark = 0.0
            for k in ("market_price", "avg_cost"):
                try:
                    v = float(pos.get(k) or 0)
                except (TypeError, ValueError):
                    v = 0.0
                if v > 0:
                    mark = v
                    break
            if mark:
                if sv and sv > 0 and ((long_pos and sv >= mark) or (not long_pos and sv <= mark)):
                    reasons.append(f"stop {sv:g} is on the wrong side of the market (~{mark:g})")
                if tv and tv > 0 and ((long_pos and tv <= mark) or (not long_pos and tv >= mark)):
                    reasons.append(f"target {tv:g} is on the wrong side of the market (~{mark:g})")
            close_action = "SELL" if long_pos else "BUY"
            open_orders = _position_orders(acct, pos)
            closing = [o for o in open_orders
                       if str(o.get("action") or "").upper() == close_action]
            entries = [o for o in open_orders
                       if str(o.get("action") or "").upper() != close_action]
            if closing:
                reasons.append(f"{len(closing)} closing exit(s) already working -- cancel or modify instead")
            if entries:
                reasons.append("same-direction entry/add order already working")

    if t in ("trim_readd", "add_to_position"):
        if not sym:
            reasons.append("symbol required")
            pos = None
        else:
            matches = _find_positions(acct, p)
            pos = matches[0] if len(matches) == 1 else None
            if not matches:
                reasons.append(f"no exact open position in {sym} ({acct})")
            elif len(matches) > 1:
                reasons.append(f"{len(matches)} positions match {sym}; exact con_id/expiry required")
        if pos is not None:
            if str(pos.get("sec_type") or "").upper() != "STK":
                reasons.append("fast trim/re-add and add actions are stock-only initially")
            try:
                expected = float(p.get("expected_position"))
            except (TypeError, ValueError):
                reasons.append("expected_position is required and must be a number")
                expected = None
            live_position = float(pos.get("position") or 0)
            if expected is not None and expected != live_position:
                reasons.append(f"stale position: expected {expected:g}, live {live_position:g}")
            held = int(round(abs(live_position)))
            qty, qty_err = _fast_qty(held, p, partial=(t == "trim_readd"))
            if qty_err:
                reasons.append(qty_err)
            exits, bracket_reasons = _bracket_snapshot(acct, pos)
            reasons.extend(bracket_reasons)
            if t == "trim_readd":
                if str(p.get("close_order_type") or "MKT").upper() != "MKT":
                    reasons.append("trim_readd is fill-gated MKT only")
                readd = p.get("readd", True)
                if not isinstance(readd, bool):
                    reasons.append("readd must be true or false")
                if readd and str(p.get("readd_tif") or "DAY").upper() != "DAY":
                    reasons.append("initial re-add order must use DAY tif")
                try:
                    avg = float(pos.get("avg_cost") or 0)
                except (TypeError, ValueError):
                    avg = 0
                if readd and not avg > 0:
                    reasons.append("live average cost unavailable; cannot stage re-add at Avg")
                adds_exposure = bool(readd)
                if qty is not None and not bracket_reasons:
                    for label, total in (("remaining", held - qty), ("re-add", qty)):
                        if label == "re-add" and not readd:
                            continue
                        _, scale_err = _scaled_snapshot_legs(exits, total)
                        if scale_err:
                            reasons.append(f"{label} bracket: {scale_err}")
            else:
                if str(p.get("order_type") or "MKT").upper() != "MKT":
                    reasons.append("add_to_position is fill-gated MKT only")
                adds_exposure = True
                try:
                    avg = max(float(pos.get("avg_cost") or 0),
                              float(pos.get("market_price") or 0))
                except (TypeError, ValueError):
                    avg = 0
                if not avg > 0:
                    reasons.append("live average/market price unavailable for notional gate")
                if qty is not None and not bracket_reasons:
                    _, scale_err = _scaled_snapshot_legs(exits, held + qty)
                    if scale_err:
                        reasons.append(f"resized bracket: {scale_err}")
            if qty is not None and adds_exposure:
                if LIVE_MAX_QTY > 0 and qty > LIVE_MAX_QTY:
                    reasons.append(f"add qty {qty} exceeds LIVE_MAX_QTY {LIVE_MAX_QTY:g}")
                if avg > 0:
                    cap = _acct_max_notional(acct)
                    if qty * avg > cap:
                        reasons.append(f"add notional ${qty * avg:,.0f} exceeds ${cap:,.0f} {acct} cap")

    if t in ("flatten", "close_only", "close_resize"):
        qty_p = p.get("qty")
        if qty_p not in (None, ""):
            # absolute share count takes precedence over fraction
            try:
                qv = float(qty_p)
            except (TypeError, ValueError):
                reasons.append("qty must be a number")
            else:
                if qv <= 0 or qv != int(qv):
                    reasons.append("qty must be a whole number > 0")
                else:
                    pos = _find_position(acct, p if t in ("close_only", "close_resize") else sym)
                    held = abs(float((pos or {}).get("position") or 0))
                    if held and qv > held:
                        reasons.append(f"qty {qv:g} exceeds held {held:g}")
        else:
            frac = p.get("fraction", 1.0)
            try:
                fv = 1.0 if frac in (None, "") else float(frac)
            except (TypeError, ValueError):
                reasons.append("fraction must be a number")
            else:
                if not (0.0 < fv <= 1.0):     # clamp: a flatten only ever closes <= the held size
                    reasons.append("fraction must be in (0, 1]")
        if t in ("close_only", "close_resize"):
            pos = _find_position(acct, p)
            if pos is not None:
                required = "SELL" if float(pos.get("position") or 0) > 0 else "BUY"
                action = str(p.get("action") or "").upper()
                if action not in ("BUY", "SELL"):
                    reasons.append("close action BUY or SELL is required")
                elif action != required:
                    reasons.append(f"{action} would add to the live position; {required} is required")
        ot = str(p.get("order_type") or "MKT").upper()
        if ot not in ("MKT", "LMT"):
            reasons.append(f"unsupported close order_type {ot}")
        if ot == "LMT":
            try:
                lim = float(p.get("limit"))
            except (TypeError, ValueError):
                reasons.append("LMT close needs a limit price")
            else:
                if lim <= 0:
                    reasons.append("limit must be > 0")
        if p.get("outside_rth") and ot != "LMT":
            reasons.append("outside-RTH close must be a LMT (IBKR ignores MKT outside RTH)")
        if str(p.get("tif") or "DAY").upper() not in ("DAY", "GTC"):
            reasons.append("tif must be DAY or GTC")

    if t == "modify":
        if not (p.get("perm_id") or p.get("order_id")):
            reasons.append("modify needs perm_id / order_id")
        else:
            ordrec = _find_order(acct, p)
            if ordrec is None:
                reasons.append("order not found in the live book")
            vals = {}
            for k in ("new_qty", "new_limit", "new_stop"):
                v = p.get(k)
                if v in (None, ""):
                    continue
                try:
                    fv = float(v)
                except (TypeError, ValueError):
                    reasons.append(f"{k} must be a number")
                    continue
                if not fv > 0:
                    reasons.append(f"{k} must be > 0")
                vals[k] = fv
            if not vals:
                reasons.append("nothing to change (new_qty / new_limit / new_stop)")
            if ordrec is not None:
                typ = str(ordrec.get("order_type", "")).upper()
                if "new_limit" in vals and "LMT" not in typ:
                    reasons.append(f"order is {typ} -- no limit price to change")
                if "new_stop" in vals and not typ.startswith("STP"):
                    reasons.append(f"order is {typ} -- no stop trigger to change")

    if t == "entry_bracket":
        sec_type = str(p.get("sec_type", "STK")).upper()
        entry_type = str(p.get("entry_type") or "LMT").upper()
        currency = str(p.get("currency") or "USD").upper().strip()
        try:
            entry = float(p.get("entry"))
            stop = float(p["stop"]) if p.get("stop") not in (None, "") else None
            entry_cap = float(p["entry_cap"]) if p.get("entry_cap") not in (None, "") else None
            qty = float(p.get("quantity") or 0)
            action = str(p.get("action", "")).upper()
            if not sym:
                reasons.append("symbol required")
            if sec_type not in ("STK", "FUT", "CASH"):
                reasons.append(f"sec_type {sec_type} not supported (STK/FUT/CASH)")
            if entry_type not in ("LMT", "STP_LMT", "MKT", "MOO", "MOC"):
                reasons.append(f"unsupported entry_type {entry_type}")
            if entry_type == "MOC" and sec_type != "STK":
                reasons.append("MOC entry supports stocks only")
            if entry_type == "MOO" and sec_type == "CASH":
                reasons.append("MOO entry does not support FX")
            if entry_type == "STP_LMT" and sec_type != "STK":
                reasons.append("STP_LMT entry supports stocks only")
            if entry_type == "STP_LMT" and entry_cap is None:
                reasons.append("STP_LMT requires entry_cap (the limit price)")
            if entry_type != "STP_LMT" and entry_cap is not None:
                reasons.append("entry_cap applies to STP_LMT only")
            if entry_cap is not None and entry_cap <= 0:
                reasons.append("entry_cap must be > 0")
            if entry_type not in ("LMT", "STP_LMT") and p.get("expiry"):
                reasons.append("entry expiry applies to LMT/STP_LMT only")
            # orderRef strategy tag. Deliberately re-stated here rather than
            # imported from execute_order: the agent validates independently.
            # A pipe would corrupt parse_ref's field split downstream.
            strat = str(p.get("strategy") or "").strip()
            if strat:
                if len(strat) > 32:
                    reasons.append("strategy tag longer than 32 chars")
                elif not re.fullmatch(r"[A-Za-z0-9 _.-]+", strat):
                    # Spaces legal: the scan pipeline tags read 'Oversold Low
                    # Volume'. Only the pipe breaks parse_ref's field split.
                    reasons.append("strategy tag allows only letters, digits, spaces, _ . and -")
                rd = str(p.get("ref_date") or "").strip()
                if rd:
                    try:
                        datetime.date.fromisoformat(rd)
                    except ValueError:
                        reasons.append("ref_date must be a date (YYYY-MM-DD)")
            elif p.get("ref_date"):
                reasons.append("ref_date needs a strategy tag")
            if action not in ("BUY", "SELL"):
                reasons.append("action must be BUY or SELL")
            if qty <= 0 or qty != int(qty):
                reasons.append("quantity must be a whole number > 0")
            if entry <= 0:
                reasons.append("entry must be > 0")
            if stop is not None and stop <= 0:
                reasons.append("stop must be > 0")
            if stop is not None:
                if action == "BUY" and entry > 0 and stop > 0 and not stop < entry:
                    reasons.append("BUY needs stop < entry")
                if action == "SELL" and entry > 0 and stop > 0 and not entry < stop:
                    reasons.append("SELL needs entry < stop")
            # STP_LMT fills anywhere between trigger and cap, so ``worst`` (the
            # cap) is what sizing, the notional cap and the target comparison
            # must read. Mirrors the executor's independent gate.
            worst = entry_cap if entry_cap is not None and entry_cap > 0 else entry
            if entry_cap is not None and entry > 0 and entry_cap > 0:
                if action == "BUY" and not entry < entry_cap:
                    reasons.append("BUY STP_LMT needs trigger < cap")
                if action == "SELL" and not entry_cap < entry:
                    reasons.append("SELL STP_LMT needs cap < trigger")
            if sec_type == "CASH":
                if len(sym) != 3 or not sym.isalpha():
                    reasons.append("CASH symbol must be a 3-letter base currency")
                if len(currency) != 3 or not currency.isalpha() or currency == sym:
                    reasons.append("CASH currency must be a different 3-letter quote currency")
                elif "USD" not in (sym, currency):
                    reasons.append("CASH entry supports USD pairs only initially")
            if sec_type == "FUT":
                fut_expiry = str(p.get("fut_expiry") or "").strip()
                exchange = str(p.get("exchange") or "").upper().strip()
                if not (len(fut_expiry) in (6, 8) and fut_expiry.isdigit()):
                    reasons.append("FUT requires fut_expiry YYYYMM (or YYYYMMDD)")
                if exchange not in {"CME", "CBOT", "NYMEX", "COMEX"}:
                    reasons.append("FUT exchange must be CME, CBOT, NYMEX, or COMEX")
                if not str(p.get("fut_ib_symbol") or "").strip():
                    reasons.append("FUT exact IB symbol is unresolved")
                if not str(p.get("fut_trading_class") or "").strip():
                    reasons.append("FUT trading class is unresolved")
            if p.get("target") not in (None, ""):
                tgt = float(p.get("target"))
                if tgt <= 0:
                    reasons.append("target must be > 0")
                if action == "BUY" and entry > 0 and tgt > 0 and not worst < tgt:
                    reasons.append("BUY needs worst fill < target")
                if action == "SELL" and entry > 0 and tgt > 0 and not tgt < worst:
                    reasons.append("SELL needs target < worst fill")
            # Scale-out: two independent brackets whose shares sum to quantity.
            so = p.get("scaleout")
            if so:
                if not isinstance(so, dict):
                    reasons.append("scaleout must be an object")
                else:
                    try:
                        frac = float(so.get("frac"))
                    except (TypeError, ValueError):
                        frac = None
                        reasons.append("scaleout frac must be a number")
                    try:
                        near_t = float(so["target"]) if so.get("target") not in (None, "") else None
                    except (TypeError, ValueError):
                        near_t = None
                        reasons.append("scaleout target must be a number")
                    if frac is not None and not 0 < frac < 1:
                        reasons.append("scaleout frac must be between 0 and 1")
                    if so.get("target") in (None, ""):
                        reasons.append("scaleout needs a target for the near leg")
                    elif near_t is not None and entry > 0:
                        if action == "BUY" and not worst < near_t:
                            reasons.append("BUY scaleout needs worst fill < near target")
                        if action == "SELL" and not near_t < worst:
                            reasons.append("SELL scaleout needs near target < worst fill")
            # Notional & risk must carry the contract multiplier — for FUT a
            # multiplier-blind cap undercounts ~50x on ES (1 lot = $250k, not $5k).
            mult, merr = _leg_multiplier(p)
            if merr:
                reasons.append(merr)
            if mult is not None:
                # Stop-less entries have no stop-distance risk here; the
                # EXECUTOR gates them on 2xATR vs NLV (risk_ack contract).
                if sec_type == "CASH" and "USD" in (sym, currency) and entry > 0:
                    notional, risk = _fx_usd_exposure(
                        sym, currency, qty, worst, stop if stop is not None else worst)
                else:
                    notional = qty * worst * mult
                    risk = qty * abs(worst - (stop if stop is not None else worst)) * mult
                if sec_type != "CASH" and not (sec_type == "FUT" and _uncapped_futures(acct)):
                    cap = _acct_max_notional(acct)
                    if notional > cap:
                        reasons.append(f"notional ${notional:,.0f} exceeds ${cap:,.0f} {acct} cap")
                _, nlv = _account_state(acct)
                if (stop is not None and nlv and risk > MAX_RISK_PCT * nlv
                        and not (sec_type == "FUT" and _uncapped_futures(acct))):
                    reasons.append(f"risk ${risk:,.0f} exceeds {MAX_RISK_PCT * 100:.0f}% of NLV")
        except (TypeError, ValueError):
            reasons.append("entry / entry_cap / stop / target / quantity must be numbers")

    if t == "option_spread":
        action = str(p.get("action", "")).upper()
        if str(acct or "").lower() not in OPTION_ACCOUNTS:
            reasons.append(f"options execution is disabled for {acct}")
        if not sym:
            reasons.append("symbol required")
        if action not in ("BUY", "SELL"):
            reasons.append("option_spread action must be BUY or SELL")
        try:
            qty = int(p.get("quantity") or 0)
            limit = float(p.get("limit") or 0)
            claimed_risk = float(p.get("debit_risk") or 0)
        except (TypeError, ValueError):
            reasons.append("quantity / limit / debit_risk must be numbers")
            qty, limit, claimed_risk = 0, 0.0, 0.0
        if qty <= 0:
            reasons.append("quantity must be > 0")
        elif not _uncapped_options(acct) and qty > MAX_OPT_CONTRACTS:
            reasons.append(f"{qty} spreads exceeds the {MAX_OPT_CONTRACTS}-spread cap")
        if limit <= 0:
            reasons.append("limit must be > 0")
        if claimed_risk <= 0:
            reasons.append("debit_risk must be > 0")
        legs, leg_reasons = _spread_legs(p)
        reasons.extend(leg_reasons)
        if legs and qty > 0 and claimed_risk > 0:
            if (len(legs) == 1 and
                    (action != "BUY" or legs[0]["side"] != "BUY" or legs[0]["ratio"] != 1)):
                reasons.append("a single option leg must be a 1:1 BUY (naked short options stay disabled)")
            # vertical sanity: paying the width or more can never profit
            if (action == "BUY" and len(legs) == 2 and legs[0]["right"] == legs[1]["right"]
                    and legs[0]["expiry"] == legs[1]["expiry"]
                    and {legs[0]["side"], legs[1]["side"]} == {"BUY", "SELL"}):
                width = abs(legs[0]["strike"] - legs[1]["strike"])
                if width <= 0:
                    reasons.append("vertical legs share a strike")
                elif limit >= width:
                    reasons.append(f"net debit {limit:g} >= width {width:g} -- no max profit")
            risk, risk_err = option_combo_risk(action, limit, qty, legs)
            if risk_err:
                reasons.append(risk_err)
            else:
                n_contracts = qty * sum(l["ratio"] for l in legs)
                comm = OPT_COMM_PER_CONTRACT * n_contracts * 2
                calculated_unit_risk = (risk - comm) / (100.0 * qty)
                if abs(claimed_risk - calculated_unit_risk) > 0.011:
                    reasons.append(f"claimed risk {claimed_risk:g} != calculated {calculated_unit_risk:g} per spread")
                if not _uncapped_options(acct):
                    cap = _acct_max_opt_risk(acct)
                    if risk > cap:
                        reasons.append(f"option risk ${risk:,.0f} exceeds ${cap:,.0f} {acct} cap")
                _, nlv = _account_state(acct)
                if nlv and risk > MAX_RISK_PCT * nlv and not _uncapped_options(acct):
                    reasons.append(f"risk ${risk:,.0f} exceeds {MAX_RISK_PCT * 100:.0f}% of NLV")

    if t == "scheduled_option":
        if p.get("pricing_policy") != "capped_limit_v1":
            reasons.append("scheduled option requires capped-limit pricing")
        reasons.extend(_validate_scheduled_option(p, acct))

    if t == "scheduled_option_cancel":
        sid = str(p.get("schedule_id") or "")
        rec = _SCHEDULES.get(sid)
        if not sid:
            reasons.append("schedule_id required")
        elif not rec:
            reasons.append("scheduled option not found")
        elif rec.get("account") != acct:
            reasons.append("scheduled option belongs to another account")
        elif rec.get("state") != "scheduled":
            reasons.append(f"scheduled option is already {rec.get('state')}")

    return (len(reasons) == 0, reasons)

def _preview(cmd: dict):
    """The exact order chain the agent WOULD build (no IB call). Returns
    {summary, legs[]}. Mirrors sznl_entry / sznl_exit leg construction."""
    import position_action_agent
    if position_action_agent.applies(cmd):
        return position_action_agent.preview(cmd)
    t, p, acct = cmd.get("type"), (cmd.get("payload") or {}), cmd.get("account")
    if t == "scheduled_option":
        expiry = (f"specific expiry {p.get('expiry')}" if p.get("expiry_mode") == "specific"
                  else f"first listed expiry with at least {p.get('min_dte')} DTE")
        return {
            "summary": (f"At {p.get('execute_date')} {p.get('execute_time')} ET: live-chain resolve, "
                        f"premium capped at ${float(p.get('premium_budget') or 0):,.0f}; "
                        "premium capped excluding commissions; LMT may remain unfilled; trigger expires after 5 minutes"),
            "legs": [f"BUY {p.get('symbol')} {p.get('right')} nearest |delta| {p.get('target_delta')}  {expiry}  capped LMT DAY"],
        }
    if t == "scheduled_option_cancel":
        return {"summary": "cancel locally persisted instruction before it reaches IBKR", "legs": []}
    if t == "entry_bracket":
        action = str(p.get("action", "")).upper()
        qty = p.get("quantity")
        sec = str(p.get("sec_type", "STK")).upper()
        entry_type = str(p.get("entry_type") or "LMT").upper()
        display_symbol = str(p.get("symbol") or "")
        if sec == "CASH":
            display_symbol = f"{display_symbol}/{str(p.get('currency') or 'USD').upper()} CASH"
        elif sec != "STK":
            display_symbol = f"{display_symbol} {sec}"
        exit_a = "SELL" if action == "BUY" else "BUY"
        have_stop = p.get("stop") not in (None, "")
        parent_desc = (f"LMT @ {p.get('entry')}" if entry_type == "LMT"
                       else f"STP LMT  trigger {p.get('entry')} / cap {p.get('entry_cap')}"
                       if entry_type == "STP_LMT"
                       else f"{entry_type}  (risk ref {p.get('entry')})")
        parent_tif = ("OPG" if entry_type == "MOO" else
                      f"GTD {p.get('expiry')}"
                      if entry_type in ("LMT", "STP_LMT") and p.get("expiry") else "DAY")
        # A scale-out is TWO independent brackets, never one parent with a
        # partial-size child (the broker forces such a child back up to the
        # parent quantity). Preview each chain so the split is visible up front.
        so = p.get("scaleout") if isinstance(p.get("scaleout"), dict) else None
        near_q = None
        if so:
            try:
                near_q = int(round(float(qty) * float(so.get("frac"))))
                if near_q < 1 or float(qty) - near_q < 1:
                    so, near_q = None, None      # rounds below a share: no split
            except (TypeError, ValueError):
                so, near_q = None, None
        chains = ([(near_q, so.get("target"), "NEAR "),
                   (int(float(qty)) - near_q, p.get("target"), "FAR  ")]
                  if so else [(qty, p.get("target"), "")])
        legs = []
        for cq, ctgt, pre in chains:
            legs.append(f"{pre}PARENT  {action} {cq} {display_symbol}  {parent_desc}  ({parent_tif})")
            if ctgt not in (None, ""):
                legs.append(f"{pre}TARGET  {exit_a} {cq}  LMT @ {ctgt}  (OCA)")
            if have_stop:
                legs.append(f"{pre}STOP    {exit_a} {cq}  STP @ {p.get('stop')}  (OCA)")
            if p.get("time_stop"):
                legs.append(f"{pre}TIME    {exit_a} {cq}  MKT @ {p.get('time_stop')} 15:59  (OCA)")
        if len(legs) == 1:
            legs.append("UNPROTECTED -- no exit legs (managed manually)")
        # AFTER the unprotected check -- a tag line must never make a naked
        # entry look like it has an exit leg.
        strat_tag = str(p.get("strategy") or "").strip()
        if strat_tag:
            base_ref = (f"{str(p.get('symbol') or '').upper()}|{action}|{strat_tag}|"
                        f"{str(p.get('ref_date') or '').strip() or 'today'}")
            # A split stamps the tranche as the 5th field, which is how the trail
            # job tells one plan's two stops apart. Show it, or the preview lies.
            legs.append(f"TAG     every leg orderRef {base_ref}"
                        + ("|near / |far" if so else ""))
        summary = ""
        try:
            mult, _merr = _leg_multiplier(p)
            mult = mult if mult is not None else 1.0
            q, entry_f = float(qty), float(p.get("entry"))
            stop_f = float(p.get("stop")) if have_stop else None
            # Preview the WORST acceptable fill so the operator reads the number
            # the gates enforce: the cap for STP_LMT, the entry for everything else.
            worst_f = (float(p.get("entry_cap"))
                       if p.get("entry_cap") not in (None, "") else entry_f)
            if sec == "CASH":
                notional, risk = _fx_usd_exposure(
                    p.get("symbol"), p.get("currency", "USD"), q, worst_f,
                    stop_f if stop_f is not None else worst_f)
            else:
                risk = q * abs(worst_f - (stop_f if stop_f is not None else worst_f)) * mult
                notional = q * worst_f * mult
            if stop_f is not None:
                prefix = ("worst-case " if entry_type == "STP_LMT"
                          else "est. " if entry_type != "LMT" else "")
                summary = f"{prefix}risk ${risk:,.0f}  ·  {prefix}notional ${notional:,.0f}"
                if p.get("target") not in (None, ""):
                    rr = abs(float(p.get("target")) - worst_f) / abs(worst_f - stop_f)
                    summary += f"  ·  R:R {rr:.2f}:1"
            else:
                summary = (f"NO STOP  ·  notional ${notional:,.0f}  ·  "
                           "risk gate at execution: 2xATR% x notional vs 50 bps NLV")
        except (TypeError, ValueError, ZeroDivisionError):
            pass
        return {"summary": summary, "legs": legs}
    if t == "exit_attach":
        pos = _find_position(acct, p)
        if not pos or not pos.get("position"):
            return {"summary": "no matching position", "legs": []}
        held = int(round(abs(float(pos["position"]))))
        long_pos = float(pos["position"]) > 0
        close = "SELL" if long_pos else "BUY"
        legs = []
        if p.get("target") not in (None, ""):
            legs.append(f"TARGET  {close} {held} {p.get('symbol')}  LMT @ {p.get('target')}  (OCA GTC)")
        if p.get("stop") not in (None, ""):
            legs.append(f"STOP    {close} {held} {p.get('symbol')}  STP @ {p.get('stop')}  (OCA GTC)")
        if p.get("time_stop"):
            legs.append(f"TIME    {close} {held} {p.get('symbol')}  MKT @ {p.get('time_stop')} 15:59  (OCA GTC)")
        return {"summary": f"attach {len(legs)} exit leg(s) to {'LONG' if long_pos else 'SHORT'} {held}",
                "legs": legs}
    if t in ("trim_readd", "add_to_position"):
        pos = _find_position(acct, p)
        if not pos or not pos.get("position"):
            return {"summary": "nothing to change", "legs": []}
        held = int(round(abs(float(pos["position"]))))
        qty, qty_err = _fast_qty(held, p, partial=(t == "trim_readd"))
        if qty_err or qty is None:
            return {"summary": qty_err or "invalid quantity", "legs": []}
        direction = "LONG" if float(pos["position"]) > 0 else "SHORT"
        entry_action = "BUY" if direction == "LONG" else "SELL"
        close_action = "SELL" if direction == "LONG" else "BUY"
        exits, _ = _bracket_snapshot(acct, pos)
        if t == "trim_readd":
            remaining = held - qty
            legs = [f"TRIM    {close_action} {qty} {p.get('symbol')}  MKT  (fill-gated)"]
            scaled, err = _scaled_snapshot_legs(exits, remaining)
            if err:
                legs.append(f"REMAINDER BRACKET ERROR: {err}")
            else:
                legs.extend(_snapshot_leg_text("REMAIN  ", leg, n) for leg, n in scaled)
            if p.get("readd", True):
                avg = pos.get("avg_cost")
                legs.append(f"RE-ADD  {entry_action} {qty} {p.get('symbol')}  LMT @ {avg}  (DAY)")
                cloned, err = _scaled_snapshot_legs(exits, qty)
                if err:
                    legs.append(f"RE-ADD BRACKET ERROR: {err}")
                else:
                    legs.extend(_snapshot_leg_text("CHILD   ", leg, n) for leg, n in cloned)
            summary = (f"{direction} {held}: trim {qty}, protect {remaining}"
                       + (f", stage {qty} back at Avg {pos.get('avg_cost')}" if p.get("readd", True) else ""))
            return {"summary": summary, "legs": legs}
        new_total = held + qty
        legs = [f"ADD     {entry_action} {qty} {p.get('symbol')}  MKT  (fill-gated)"]
        scaled, err = _scaled_snapshot_legs(exits, new_total)
        if err:
            legs.append(f"RESIZED BRACKET ERROR: {err}")
        else:
            legs.extend(_snapshot_leg_text("RESIZE  ", leg, n) for leg, n in scaled)
        return {"summary": f"{direction} {held}: add {qty}, protect new total {new_total}",
                "legs": legs}
    if t in ("flatten", "close_only", "close_resize"):
        pos = _find_position(acct, p if t in ("close_only", "close_resize") else p.get("symbol"))
        if pos and pos.get("position"):
            q = int(round(abs(pos["position"])))
            n = _requested_close_qty(p, q)
            if n is None:
                n = 0
            close = "SELL" if pos["position"] > 0 else "BUY"
            ot = str(p.get("order_type") or "MKT").upper()
            px = f" @ {p.get('limit')}" if ot == "LMT" else ""
            rth = "  outsideRTH" if p.get("outside_rth") else ""
            tif = str(p.get("tif") or "DAY").upper()
            rem = max(0, q - n)
            close_leg = f"{close} {n} {p.get('symbol')}  {ot}{px}{rth}  ({tif})"
            if t == "close_only":
                legs = [close_leg, "LEAVE ALL WORKING ORDERS UNCHANGED"]
                suffix = ", working orders unchanged"
            elif t == "close_resize":
                # Ordering is the product here, so the preview leads with the
                # shrink: the exits come down BEFORE anything is sold. A full
                # close has no legal plan (an exit cannot be resized to zero),
                # so show the refusal rather than an impossible one.
                if rem <= 0:
                    legs = ["REFUSED — a full close cannot resize its exits to zero; use flatten"]
                    suffix = " — PARTIAL closes only"
                else:
                    legs = [f"RESIZE working exits {q} -> {rem}  (first, as the placing client)",
                            close_leg]
                    suffix = f", exits shrink to {rem} before the close"
            else:
                legs = [close_leg]
                if 0 < n < q:
                    legs.append(f"RE-ATTACH working exits @ qty {rem}")
                elif ot == "LMT" and n >= q:
                    legs.append("all exits cancelled — position rests UNPROTECTED behind the working close")
                else:
                    legs.append("CANCEL working orders first — position is unprotected until the close fills")
                suffix = f", exits resize to {rem}" if 0 < n < q else ""
            return {"summary": f"close {n} of {q}" + suffix,
                    "legs": legs}
        return {"summary": "nothing to close", "legs": []}
    if t == "cancel":
        what = f"order {p.get('order_id')}" if p.get("scope") == "order" else f"all orders for {p.get('symbol')}"
        return {"summary": "", "legs": [f"CANCEL  {what}"]}
    if t == "modify":
        o = _find_order(acct, p)
        changes = []
        if p.get("new_qty") not in (None, ""):
            old = f"{o.get('qty'):g} " if o and o.get("qty") is not None else ""
            changes.append(f"qty {old}-> {p['new_qty']}")
        if p.get("new_limit") not in (None, ""):
            old = f"{o.get('lmt'):g} " if o and o.get("lmt") else ""
            changes.append(f"lmt {old}-> {p['new_limit']}")
        if p.get("new_stop") not in (None, ""):
            old = f"{o.get('aux'):g} " if o and o.get("aux") else ""
            changes.append(f"stop {old}-> {p['new_stop']}")
        qty = f"{o['qty']:g}" if o and o.get("qty") is not None else "?"
        head = (f"MODIFY  {o.get('action')} {qty} {o.get('symbol')}  {o.get('order_type')}"
                if o else f"MODIFY  order {p.get('perm_id') or p.get('order_id')}")
        return {"summary": ", ".join(changes), "legs": [head] + [f"  {c}" for c in changes]}
    if t == "option_spread":
        legs, _r = _spread_legs(p)
        lines = []
        for l in (legs or []):
            lines.append(f"LEG     {l['side']} {l['ratio']}x {p.get('symbol')} "
                         f"{l['expiry']} {l['strike']:g}{l['right']}")
        label = "OPTION" if legs and len(legs) == 1 else "COMBO"
        route = "OPT" if legs and len(legs) == 1 else "BAG"
        lines.append(f"{label:<7} {p.get('action')} {p.get('quantity')}x  {route} LMT @ {p.get('limit')} net  "
                     f"({str(p.get('tif') or 'DAY').upper()}, SMART)")
        summary = ""
        try:
            qty = int(p.get("quantity") or 0)
            action = str(p.get("action") or "").upper()
            risk, risk_err = option_combo_risk(action, p.get("limit"), qty, legs or [])
            summary = (f"defined risk incl. round-trip commissions ~${risk:,.2f}"
                       if not risk_err else f"risk validation: {risk_err}")
            if (legs and len(legs) == 2 and legs[0]["right"] == legs[1]["right"]
                    and {legs[0]["side"], legs[1]["side"]} == {"BUY", "SELL"}):
                width = abs(legs[0]["strike"] - legs[1]["strike"])
                lim = float(p.get("limit") or 0)
                if width > 0 and lim > 0:
                    max_profit = lim if action == "SELL" else width - lim
                    summary += (f"  ·  width {width:g}  ·  max profit "
                                f"${max_profit * 100 * qty:,.0f}")
        except (TypeError, ValueError):
            pass
        return {"summary": summary, "legs": lines}
    return {"summary": "", "legs": []}

def _journal_option(cmd: dict, reply: dict) -> None:
    """One JSONL line per option_spread command (the options journal seed —
    entry context for the later positions-book/scorecard phases). Never blocks."""
    p = cmd.get("payload") or {}
    try:
        with open(OPTIONS_JOURNAL_PATH, "a", encoding="utf-8") as f:
            f.write(json.dumps({
                "id": cmd.get("id"), "ts": time.time(), "account": cmd.get("account"),
                "state": reply.get("state"), "symbol": p.get("symbol"),
                "structure": p.get("structure"), "action": p.get("action"),
                "qty": p.get("quantity"), "limit": p.get("limit"),
                "debit_risk": p.get("debit_risk"), "legs": p.get("legs"),
                "strategy": p.get("strategy"), "signal_date": p.get("signal_date"),
                "dry_run": bool(cmd.get("dry_run")),
            }) + "\n")
    except Exception as e:  # noqa: BLE001
        log(f"options-journal write failed: {e}")

def _live_eligible(cmd: dict):
    """Agent-side live gate (execute_order.py re-checks independently). Off unless
    armed. Returns (eligible, reason)."""
    if not LIVE_ENABLED:
        return False, "AGENT_LIVE_ENABLED off"
    if cmd.get("account") not in LIVE_ACCOUNTS:
        return False, f"account {cmd.get('account')} not armed"
    p = cmd.get("payload") or {}
    if cmd.get("type") == "scheduled_option" or p.get("dynamic_selection"):
        if p.get("order_type") != "LMT" or p.get("pricing_policy") != "capped_limit_v1":
            return False, "scheduled option requires capped-limit pricing"
    armed_type = "option_spread" if cmd.get("type") in {"scheduled_option", "scheduled_option_cancel"} else cmd.get("type")
    if armed_type in DISABLED_UNSAFE_MUTATIONS - {"add_to_position", "cancel", "modify"}:
        return False, f"type {armed_type} is disabled pending an atomic broker lifecycle"
    if armed_type not in LIVE_TYPES:
        return False, f"type {armed_type} not armed"
    return True, ""

async def _execute_live_unlocked(cmd: dict):
    """Invoke the gated execute_order.py subprocess — the ONLY transmit path.
    Returns its result dict, an error dict, or (on timeout) an 'unknown' dict:
    a timed-out child may already have transmitted, so the UI must NOT read it
    as a clean failure and invite a resubmit."""
    try:
        proc = await asyncio.create_subprocess_exec(
            sys.executable, EXECUTE_SCRIPT, json.dumps(cmd),
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL)
    except Exception as e:  # noqa: BLE001
        return {"ok": False, "state": "error", "detail": f"execute subprocess error: {e}"}
    try:
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=EXECUTE_TIMEOUT_S)
        try:
            result = json.loads((out or b"").decode())
        except Exception:  # noqa: BLE001 - child may have transmitted already
            result = None
        valid = (
            proc.returncode == 0
            and isinstance(result, dict)
            and type(result.get("ok")) is bool
            and result.get("state") in {"executed", "rejected", "unknown"}
            and isinstance(result.get("detail"), str)
            and bool(result.get("detail"))
            and (result["state"] == "executed") == result["ok"]
        )
        if not valid:
            return {
                "ok": False,
                "state": "unknown",
                "detail": (
                    "execute child returned no trustworthy terminal result; "
                    "transmit status is unknown -- VERIFY IN TWS AND DO NOT RETRY"
                ),
            }
        return result
    except asyncio.TimeoutError:
        try:                                     # kill the orphan (mirrors _fetch_book)
            proc.kill()
        except Exception:  # noqa: BLE001
            pass
        try:
            await proc.communicate()
        except Exception:  # noqa: BLE001
            pass
        return {"ok": False, "state": "unknown",
                "detail": (f"execute timed out after {EXECUTE_TIMEOUT_S}s; "
                           "transmit status unknown - VERIFY IN TWS before retrying")}
    except Exception as e:  # noqa: BLE001
        return {
            "ok": False,
            "state": "unknown",
            "detail": (
                f"execute subprocess result failed ({type(e).__name__}); "
                "transmit status is unknown -- VERIFY IN TWS AND DO NOT RETRY"
            ),
        }

async def _execute_live(cmd):
    global _POSITION_EXEC_LOCK
    if _POSITION_EXEC_LOCK is None:
        _POSITION_EXEC_LOCK = asyncio.Lock()
    async with _POSITION_EXEC_LOCK:
        return await _execute_live_unlocked(cmd)

async def _send_schedule_result(ws, rec: dict, state: str, ok: bool, detail: str,
                                preview=None, fill=None) -> None:
    message = {
        "type": "result", "id": rec.get("id"), "state": state, "ok": ok,
        "detail": detail, "validation": {"ok": ok, "reasons": [] if ok else [detail]},
        "preview": preview or _preview({"type": "scheduled_option",
                                         "account": rec.get("account"),
                                         "payload": rec.get("payload") or {}}),
        "fill": fill, "at": time.time(),
    }
    try:
        await ws.send(json.dumps(message))
    except Exception as e:  # noqa: BLE001 -- local state remains authoritative
        log(f"scheduled option status push failed: {e}")

async def _scheduled_option_loop(ws) -> None:
    """Resolve and execute each persisted intent once, inside its short grace window."""
    synced = set()
    while True:
        now = time.time()
        for rec in list(_SCHEDULES.values()):
            if rec.get("state") == "executing":
                rec["state"] = "unknown"
                rec["completed_at"] = time.time()
                rec["detail"] = "agent reconnected during execution; VERIFY IN TWS -- never auto-retried"
                _save_schedules()
            # Reconcile terminal states after a WebSocket reconnect. This makes a
            # result reached while the relay was unavailable visible again.
            if rec.get("state") != "scheduled" and rec.get("id") not in synced:
                terminal_ok = rec.get("state") in ("executed", "cancelled")
                await _send_schedule_result(ws, rec, rec.get("state") or "unknown",
                                            terminal_ok, rec.get("detail") or rec.get("state") or "unknown",
                                            fill=rec.get("fill"))
                synced.add(rec.get("id"))
                continue
            if rec.get("state") != "scheduled":
                continue
            if now > float(rec.get("expires_at") or 0):
                rec["state"] = "expired"
                rec["detail"] = "execution window expired before the agent could run; nothing sent"
                _save_schedules()
                await _send_schedule_result(ws, rec, "expired", False, rec["detail"])
                log(f"scheduled option {rec.get('id')} EXPIRED")
                continue
            if now < float(rec.get("execute_at") or 0):
                continue

            # Persist BEFORE spawning the transmit subprocess. A crash from here on
            # becomes UNKNOWN on restart and is never automatically retried.
            rec["state"] = "executing"
            rec["started_at"] = now
            _save_schedules()
            await _send_schedule_result(ws, rec, "executing", True,
                                        "trigger reached; resolving the live chain")
            payload = dict(rec.get("payload") or {})
            payload["dynamic_selection"] = True
            derived = {"id": rec.get("id"), "type": "option_spread",
                       "account": rec.get("account"), "payload": payload}
            eligible, reason = _live_eligible(derived)
            if not eligible:
                result = {"ok": False, "state": "rejected",
                          "detail": f"scheduled option live gate: {reason}", "fill": None}
            else:
                try:
                    result = await asyncio.shield(_execute_live(derived))
                    _journal_option(derived, result)
                except asyncio.CancelledError:
                    # The subprocess may already have transmitted. Persist UNKNOWN
                    # and never retry after a relay disconnect or agent shutdown.
                    rec["state"] = "unknown"
                    rec["completed_at"] = time.time()
                    rec["detail"] = "agent connection ended during execution; VERIFY IN TWS -- never auto-retried"
                    _save_schedules()
                    raise
            state = result.get("state") or "unknown"
            rec["state"] = state
            rec["completed_at"] = time.time()
            rec["detail"] = result.get("detail") or state
            rec["fill"] = result.get("fill")
            _save_schedules()
            await _send_schedule_result(ws, rec, state, bool(result.get("ok")),
                                        rec["detail"], fill=result.get("fill"))
            synced.add(rec.get("id"))
            log(f"scheduled option {rec.get('id')} -> {rec['detail']}")
        await asyncio.sleep(1)

async def _handle_command(ws, signed: str, sig: str) -> None:
    reply = {"type": "result", "at": time.time()}
    try:
        if not _verify(signed, sig):
            try:
                reply["id"] = json.loads(signed).get("id")
            except Exception:
                reply["id"] = None
            reply.update(state="rejected", ok=False, detail="bad signature")
            await ws.send(json.dumps(reply))
            log("command REJECTED (bad signature)")
            return
        cmd = json.loads(signed)
        reply["id"] = cmd.get("id")
        if time.time() * 1000 > float(cmd.get("expires_at", 0)):
            reply.update(state="rejected", ok=False, detail="expired")
            await ws.send(json.dumps(reply))
            log(f"command {cmd.get('id')} REJECTED (expired)")
            return
        cid = str(cmd.get("id") or "").strip()
        if not cid:
            reply.update(state="rejected", ok=False, detail="command id is required")
            await ws.send(json.dumps(reply))
            return
        if cid in _SEEN:                                  # idempotency: never re-process
            reply.update(state="duplicate", ok=True, detail="duplicate command ignored")
            await ws.send(json.dumps(reply))
            return
        try:
            claimed = _claim_seen(cid, cmd.get("type"))
        except Exception as exc:  # noqa: BLE001 — fail closed before any subprocess
            reply.update(
                state="rejected",
                ok=False,
                detail=(
                    f"durable command receipt unavailable ({type(exc).__name__}); "
                    "nothing executed"
                ),
            )
            await ws.send(json.dumps(reply))
            log(f"command {cid} REJECTED (durable receipt unavailable: {exc})")
            return
        if not claimed:
            if cid not in _SEEN:
                _SEEN.append(cid)
            reply.update(state="duplicate", ok=True, detail="duplicate command ignored")
            await ws.send(json.dumps(reply))
            return
        _SEEN.append(cid)
        if len(_SEEN) > 200:
            del _SEEN[:100]
        desc = _describe(cmd)
        ok, reasons = _validate(cmd)
        preview = _preview(cmd)
        # HARD dry-run: never constructs or transmits an order. Validation says
        # whether it WOULD be accepted live; preview is the exact order chain.
        if ok and cmd.get("type") == "scheduled_option_cancel":
            sid = str((cmd.get("payload") or {}).get("schedule_id") or "")
            rec = _SCHEDULES[sid]
            rec["state"] = "cancelled"
            rec["completed_at"] = time.time()
            rec["detail"] = "cancelled by user before trigger; nothing sent"
            _save_schedules()
            await _send_schedule_result(ws, rec, "cancelled", True, rec["detail"])
            reply.update(state="cancelled", ok=True, detail=f"cancelled schedule {sid}",
                         validation={"ok": True, "reasons": []}, preview=preview)
            log(f"command {cmd.get('id')} [scheduled_option_cancel] -> {sid} cancelled")
        elif ok and cmd.get("type") == "scheduled_option":
            eligible, _reason = _live_eligible(cmd)
            dry_flag = bool(cmd.get("dry_run")) or bool((cmd.get("payload") or {}).get("dry_run"))
            if eligible and not dry_flag:
                rec = _store_schedule(cmd)
                when = datetime.datetime.fromtimestamp(rec["execute_at"], _ET)
                reply.update(state="scheduled", ok=True,
                             detail=f"scheduled for {when:%Y-%m-%d %H:%M ET}; agent will resolve live chain at trigger",
                             validation={"ok": True, "reasons": []}, preview=preview)
                log(f"command {cmd.get('id')} [scheduled_option] STORED for {when.isoformat()}")
            else:
                reply.update(state="dry_run", ok=True,
                             detail=f"[DRY-RUN] validated but did not persist schedule: {desc}",
                             validation={"ok": True, "reasons": []}, preview=preview)
                log(f"command {cmd.get('id')} [scheduled_option] DRY-RUN ok (not persisted)")
        elif ok:
            eligible, _reason = _live_eligible(cmd)
            # A signed dry_run flag forces the hard dry-run path even when armed
            # (defence in depth alongside AGENT_LIVE_ENABLED) -- the transmit
            # subprocess is never spawned.
            dry_flag = bool(cmd.get("dry_run")) or bool((cmd.get("payload") or {}).get("dry_run"))
            if eligible and not dry_flag:
                res = await _execute_live(cmd)          # gated transmit (armed only)
                reply.update(state=res["state"], ok=res["ok"],
                             detail=res["detail"], validation={"ok": True, "reasons": []},
                             preview=preview, fill=res.get("fill"))
                log(f"command {cmd.get('id')} [{cmd.get('type')}] LIVE -> {res.get('detail')}")
            else:
                reply.update(state="dry_run", ok=True, detail=f"[DRY-RUN] would {desc}",
                             validation={"ok": True, "reasons": []}, preview=preview)
                log(f"command {cmd.get('id')} [{cmd.get('type')}] DRY-RUN ok -> would {desc}")
        else:
            reply.update(state="rejected", ok=False,
                         detail="validation: " + "; ".join(reasons),
                         validation={"ok": False, "reasons": reasons}, preview=preview)
            log(f"command {cmd.get('id')} [{cmd.get('type')}] REJECTED -> {'; '.join(reasons)}")
        _record_seen(cid, cmd.get("type"), reply.get("state"))
        if cmd.get("type") == "option_spread":
            _journal_option(cmd, reply)
        await ws.send(json.dumps(reply))
    except Exception as e:  # noqa: BLE001
        reply.update(
            state="unknown",
            ok=False,
            detail=(
                f"command processing became indeterminate ({type(e).__name__}); "
                "VERIFY IN TWS AND DO NOT RETRY"
            ),
        )
        try:
            await ws.send(json.dumps(reply))
        except Exception:
            pass
        log(f"command error: {e}")

async def _fetch_option(ticker: str, expiry: str = None):
    """Run option_quote.py (read-only) for a ticker; returns the spread-R/R dict."""
    args = [sys.executable, OPTION_SCRIPT, ticker]
    if expiry:
        args.append(expiry)
    proc = None
    try:
        proc = await asyncio.create_subprocess_exec(
            *args, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL)
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=70)
        return json.loads((out or b"").decode() or "{}")
    except Exception as e:  # noqa: BLE001
        return {"error": f"option fetch ({type(e).__name__})", "ticker": ticker}
    finally:
        if proc is not None:
            if proc.returncode is None:
                try:
                    proc.kill()
                except ProcessLookupError:
                    pass
            await proc.communicate()

async def _fetch_workbench(query: dict):
    """Run option_workbench.py (read-only) — term structure + chain band."""
    proc = None
    try:
        proc = await asyncio.create_subprocess_exec(
            sys.executable, WORKBENCH_SCRIPT, json.dumps(query),
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL)
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=70)
        return json.loads((out or b"").decode() or "{}")
    except Exception as e:  # noqa: BLE001
        return {"error": f"workbench fetch ({type(e).__name__})", "ticker": query.get("ticker")}
    finally:
        if proc is not None:
            if proc.returncode is None:
                try:
                    proc.kill()
                except ProcessLookupError:
                    pass
            await proc.communicate()

async def _fetch_futures_front(symbol: str, exchange: str | None = None):
    """Run futures_front.py (read-only reqContractDetails) for a symbol; returns
    {symbol, exchange, expiry, expiries[]} or {error}."""
    proc = None
    try:
        proc = await asyncio.create_subprocess_exec(
            sys.executable, FUTURES_FRONT_SCRIPT, symbol, str(exchange or ""),
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL)
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=30)
        return json.loads((out or b"").decode() or "{}")
    except Exception as e:  # noqa: BLE001
        return {"error": f"front-month fetch ({type(e).__name__})", "symbol": symbol}
    finally:
        if proc is not None:
            if proc.returncode is None:
                try:
                    proc.kill()
                except ProcessLookupError:
                    pass
            await proc.communicate()

async def _fetch_book():
    """Run book_snapshot.py (read-only) as a subprocess and return the parsed book,
    or None on failure. Isolated process so ib_insync's loop never touches ours."""
    proc = None
    try:
        proc = await asyncio.create_subprocess_exec(
            sys.executable, BOOK_SNAPSHOT,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL)
        try:
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=30)
        except asyncio.TimeoutError:
            try:
                proc.kill()
            except Exception:
                pass
            return None
        return json.loads((stdout or b"").decode() or "{}")
    except NotImplementedError:
        log("_fetch_book: subprocess not supported on this loop")
        return None
    except Exception as e:  # noqa: BLE001
        log(f"_fetch_book error: {type(e).__name__}: {e}")
        return None
    finally:
        if proc is not None:
            if proc.returncode is None:
                try:
                    proc.kill()
                except ProcessLookupError:
                    pass
            await proc.communicate()

def _connect(url: str, headers: dict):
    """websockets.connect with the auth header, tolerant of the lib's header-kwarg
    rename (additional_headers in >=12, extra_headers before).

    ping_interval=None disables the client's WS-level pings: the hibernating
    Durable Object doesn't pong them, so the default ping timeout was tearing the
    socket down every ~20s. Our app-level heartbeat (every 10s) is the keepalive
    and liveness check instead — a failed send surfaces a dead link and triggers
    reconnect."""
    try:
        return websockets.connect(url, additional_headers=headers, open_timeout=15,
                                  ping_interval=None)
    except TypeError:
        return websockets.connect(url, extra_headers=headers, open_timeout=15,
                                  ping_interval=None)

async def _run_once() -> None:
    headers = {"Authorization": f"Bearer {TOKEN}"}
    async with _connect(WS_URL, headers) as ws:
        await ws.send(json.dumps({"type": "hello", "agent": "exec_agent",
                                  "pid": os.getpid(), "t": time.time()}))
        log(f"connected -> {WS_URL}")

        async def beat() -> None:
            while True:
                await asyncio.sleep(HEARTBEAT_S)
                if not in_window():
                    log("end of run window; closing")
                    await ws.close()
                    return
                await ws.send(json.dumps({"type": "heartbeat", "t": time.time()}))

        async def book_loop() -> None:
            # push a read-only book on connect, then refresh on a cadence
            while True:
                try:
                    book = await _fetch_book()
                    if book is not None:
                        # "live" only when explicitly armed (AGENT_LIVE_ENABLED=1);
                        # otherwise hard dry-run. Drives the UI banner.
                        book["mode"] = "live" if LIVE_ENABLED else "dry-run"
                        _BOOK["book"] = book
                        await ws.send(json.dumps({"type": "book", "book": book, "at": time.time()}))
                except Exception as e:  # noqa: BLE001
                    log(f"book_loop error: {e}")
                await asyncio.sleep(BOOK_REFRESH_S)

        hb = asyncio.create_task(beat())
        bk = asyncio.create_task(book_loop())
        so = asyncio.create_task(_scheduled_option_loop(ws))
        import position_action_agent
        pa = asyncio.create_task(position_action_agent.loop(globals(), ws))
        try:
            async for raw in ws:
                try:
                    msg = json.loads(raw)
                except Exception:
                    msg = {"type": "raw", "data": raw}
                if msg.get("type") == "command":
                    await _handle_command(ws, msg.get("signed", ""), msg.get("sig", ""))
                elif msg.get("type") == "option_query":      # read-only spread R/R
                    data = await _fetch_option(msg.get("ticker", ""), msg.get("expiry"))
                    await ws.send(json.dumps({"type": "option_result", "id": msg.get("id"),
                                              "ticker": msg.get("ticker"), "data": data}))
                    log(f"option_query {msg.get('ticker')} -> {'ok' if not data.get('error') else data.get('error')}")
                elif msg.get("type") == "workbench_query":    # read-only chain + term structure
                    q = {k: msg.get(k) for k in ("ticker", "mode", "expiry", "max_expiries", "context")
                         if msg.get(k) is not None}
                    data = await _fetch_workbench(q)
                    await ws.send(json.dumps({"type": "workbench_result", "id": msg.get("id"),
                                              "ticker": msg.get("ticker"), "data": data}))
                    log(f"workbench_query {msg.get('ticker')} [{q.get('mode', 'full')}] -> "
                        f"{'ok' if not data.get('error') else data.get('error')}")
                elif msg.get("type") == "futures_size":       # read-only risk sizing (pure, no IBKR)
                    data = _futures_size(msg)
                    await ws.send(json.dumps({"type": "futures_result", "id": msg.get("id"),
                                              "symbol": msg.get("symbol"), "data": data}))
                    log(f"futures_size {msg.get('symbol')} -> "
                        f"{data.get('contracts') if not data.get('error') else data.get('error')}")
                elif msg.get("type") == "futures_front":       # read-only front-month resolve
                    data = await _fetch_futures_front(msg.get("symbol", ""), msg.get("exchange"))
                    await ws.send(json.dumps({"type": "futures_front_result", "id": msg.get("id"),
                                              "symbol": msg.get("symbol"), "data": data}))
                    log(f"futures_front {msg.get('symbol')} -> {data.get('expiry') or data.get('error')}")
                elif msg.get("type") != "ack":
                    log(f"<- {msg}")
        finally:
            hb.cancel()
            bk.cancel()
            so.cancel()
            pa.cancel()
            await asyncio.gather(hb, bk, so, pa, return_exceptions=True)

async def main() -> None:
    if not WS_URL or not TOKEN:
        raise SystemExit("Set EXEC_BROKER_WS and EXEC_AGENT_TOKEN env vars first.")
    _load_seen()                         # dedup survives restarts (last 24h of ids)
    _load_schedules()                    # pending dynamic option intents survive restarts
    backoff = 1
    while True:
        if not in_window():
            log(f"outside run window {START_HOUR:02d}:00-{END_HOUR:02d}:00 (local); exiting")
            return
        try:
            await _run_once()
            backoff = 1                      # clean exit -> reset backoff
        except Exception as e:  # noqa: BLE001 — keep the agent alive across drops
            log(f"disconnected: {e}; retry in {backoff}s")
        await asyncio.sleep(backoff)
        backoff = min(BACKOFF_MAX_S, backoff * 2)
